[BridgeIO]
BridgeIO_IP=10.66.9.111
[HostVehicle]
Vehicle_ID=0
[DDS]
Domain=0
# 1: udp 2: tcp 3: udp6 4: tcp6 5: sm
Transport=1
Sub_TCP_IP=10.66.9.244
Sub_TCP_PORTBASE=5102
Pub_TCP_PORTBASE=5100
# 0 BEST_EFFORT_RELIABILITY_QOS 1 RELIABLE_RELIABILITY_QOS
Kind=1
W_Topic_GPS=BenchMarkTopicTCP
W_Topic_Obstacle=Obstacle
W_Topic_Control=Control
[Sensor]
ENABLED=0
IMG_IP=10.66.9.244
IMG_PORT=13956
PCD_IP=10.66.9.244
PCD_PORT=6699
PCD_PORT_INFO=7788
PCD_FRAMEID=velodyne128
