// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file SimOne_Data_Control.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "SimOne_Data_Control.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>





SimOneDDS_Data_Control::SimOneDDS_Data_Control()
{
    // m_throttleMode com.eprosima.idl.parser.typecode.EnumTypeCode@76b10754
    m_throttleMode = ::ESimOneDDS_Throttle_Mode_Percent;
    // m_throttle com.eprosima.idl.parser.typecode.PrimitiveTypeCode@2bea5ab4
    m_throttle = 0.0;
    // m_brakeMode com.eprosima.idl.parser.typecode.EnumTypeCode@3d8314f0
    m_brakeMode = ::ESimOneDDS_Brake_Mode_Percent;
    // m_brake com.eprosima.idl.parser.typecode.PrimitiveTypeCode@2df32bf7
    m_brake = 0.0;
    // m_steeringMode com.eprosima.idl.parser.typecode.EnumTypeCode@530612ba
    m_steeringMode = ::ESimOneDDS_Steering_Mode_Percent;
    // m_steering com.eprosima.idl.parser.typecode.PrimitiveTypeCode@2a40cd94
    m_steering = 0.0;
    // m_handbrake com.eprosima.idl.parser.typecode.PrimitiveTypeCode@f4168b8
    m_handbrake = false;
    // m_isManualGear com.eprosima.idl.parser.typecode.PrimitiveTypeCode@74294adb
    m_isManualGear = false;
    // m_gear com.eprosima.idl.parser.typecode.EnumTypeCode@70a9f84e
    m_gear = ::ESimOneDDS_Gear_Mode_Neutral;

}

SimOneDDS_Data_Control::~SimOneDDS_Data_Control()
{









}

SimOneDDS_Data_Control::SimOneDDS_Data_Control(
        const SimOneDDS_Data_Control& x)
{
    m_throttleMode = x.m_throttleMode;
    m_throttle = x.m_throttle;
    m_brakeMode = x.m_brakeMode;
    m_brake = x.m_brake;
    m_steeringMode = x.m_steeringMode;
    m_steering = x.m_steering;
    m_handbrake = x.m_handbrake;
    m_isManualGear = x.m_isManualGear;
    m_gear = x.m_gear;
}

SimOneDDS_Data_Control::SimOneDDS_Data_Control(
        SimOneDDS_Data_Control&& x)
{
    m_throttleMode = x.m_throttleMode;
    m_throttle = x.m_throttle;
    m_brakeMode = x.m_brakeMode;
    m_brake = x.m_brake;
    m_steeringMode = x.m_steeringMode;
    m_steering = x.m_steering;
    m_handbrake = x.m_handbrake;
    m_isManualGear = x.m_isManualGear;
    m_gear = x.m_gear;
}

SimOneDDS_Data_Control& SimOneDDS_Data_Control::operator =(
        const SimOneDDS_Data_Control& x)
{

    m_throttleMode = x.m_throttleMode;
    m_throttle = x.m_throttle;
    m_brakeMode = x.m_brakeMode;
    m_brake = x.m_brake;
    m_steeringMode = x.m_steeringMode;
    m_steering = x.m_steering;
    m_handbrake = x.m_handbrake;
    m_isManualGear = x.m_isManualGear;
    m_gear = x.m_gear;

    return *this;
}

SimOneDDS_Data_Control& SimOneDDS_Data_Control::operator =(
        SimOneDDS_Data_Control&& x)
{

    m_throttleMode = x.m_throttleMode;
    m_throttle = x.m_throttle;
    m_brakeMode = x.m_brakeMode;
    m_brake = x.m_brake;
    m_steeringMode = x.m_steeringMode;
    m_steering = x.m_steering;
    m_handbrake = x.m_handbrake;
    m_isManualGear = x.m_isManualGear;
    m_gear = x.m_gear;

    return *this;
}

bool SimOneDDS_Data_Control::operator ==(
        const SimOneDDS_Data_Control& x) const
{

    return (m_throttleMode == x.m_throttleMode && m_throttle == x.m_throttle && m_brakeMode == x.m_brakeMode && m_brake == x.m_brake && m_steeringMode == x.m_steeringMode && m_steering == x.m_steering && m_handbrake == x.m_handbrake && m_isManualGear == x.m_isManualGear && m_gear == x.m_gear);
}

bool SimOneDDS_Data_Control::operator !=(
        const SimOneDDS_Data_Control& x) const
{
    return !(*this == x);
}

size_t SimOneDDS_Data_Control::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 1 + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);


    current_alignment += 1 + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);



    return current_alignment - initial_alignment;
}

size_t SimOneDDS_Data_Control::getCdrSerializedSize(
        const SimOneDDS_Data_Control& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 1 + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);


    current_alignment += 1 + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);



    return current_alignment - initial_alignment;
}

void SimOneDDS_Data_Control::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << (uint32_t)m_throttleMode;
    scdr << m_throttle;
    scdr << (uint32_t)m_brakeMode;
    scdr << m_brake;
    scdr << (uint32_t)m_steeringMode;
    scdr << m_steering;
    scdr << m_handbrake;
    scdr << m_isManualGear;
    scdr << (uint32_t)m_gear;

}

void SimOneDDS_Data_Control::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    {
        uint32_t enum_value = 0;
        dcdr >> enum_value;
        m_throttleMode = (ESimOneDDS_Throttle_Mode)enum_value;
    }

    dcdr >> m_throttle;
    {
        uint32_t enum_value = 0;
        dcdr >> enum_value;
        m_brakeMode = (ESimOneDDS_Brake_Mode)enum_value;
    }

    dcdr >> m_brake;
    {
        uint32_t enum_value = 0;
        dcdr >> enum_value;
        m_steeringMode = (ESimOneDDS_Steering_Mode)enum_value;
    }

    dcdr >> m_steering;
    dcdr >> m_handbrake;
    dcdr >> m_isManualGear;
    {
        uint32_t enum_value = 0;
        dcdr >> enum_value;
        m_gear = (ESimOneDDS_Gear_Mode)enum_value;
    }

}

/*!
 * @brief This function sets a value in member throttleMode
 * @param _throttleMode New value for member throttleMode
 */
void SimOneDDS_Data_Control::throttleMode(
        ESimOneDDS_Throttle_Mode _throttleMode)
{
    m_throttleMode = _throttleMode;
}

/*!
 * @brief This function returns the value of member throttleMode
 * @return Value of member throttleMode
 */
ESimOneDDS_Throttle_Mode SimOneDDS_Data_Control::throttleMode() const
{
    return m_throttleMode;
}

/*!
 * @brief This function returns a reference to member throttleMode
 * @return Reference to member throttleMode
 */
ESimOneDDS_Throttle_Mode& SimOneDDS_Data_Control::throttleMode()
{
    return m_throttleMode;
}

/*!
 * @brief This function sets a value in member throttle
 * @param _throttle New value for member throttle
 */
void SimOneDDS_Data_Control::throttle(
        float _throttle)
{
    m_throttle = _throttle;
}

/*!
 * @brief This function returns the value of member throttle
 * @return Value of member throttle
 */
float SimOneDDS_Data_Control::throttle() const
{
    return m_throttle;
}

/*!
 * @brief This function returns a reference to member throttle
 * @return Reference to member throttle
 */
float& SimOneDDS_Data_Control::throttle()
{
    return m_throttle;
}

/*!
 * @brief This function sets a value in member brakeMode
 * @param _brakeMode New value for member brakeMode
 */
void SimOneDDS_Data_Control::brakeMode(
        ESimOneDDS_Brake_Mode _brakeMode)
{
    m_brakeMode = _brakeMode;
}

/*!
 * @brief This function returns the value of member brakeMode
 * @return Value of member brakeMode
 */
ESimOneDDS_Brake_Mode SimOneDDS_Data_Control::brakeMode() const
{
    return m_brakeMode;
}

/*!
 * @brief This function returns a reference to member brakeMode
 * @return Reference to member brakeMode
 */
ESimOneDDS_Brake_Mode& SimOneDDS_Data_Control::brakeMode()
{
    return m_brakeMode;
}

/*!
 * @brief This function sets a value in member brake
 * @param _brake New value for member brake
 */
void SimOneDDS_Data_Control::brake(
        float _brake)
{
    m_brake = _brake;
}

/*!
 * @brief This function returns the value of member brake
 * @return Value of member brake
 */
float SimOneDDS_Data_Control::brake() const
{
    return m_brake;
}

/*!
 * @brief This function returns a reference to member brake
 * @return Reference to member brake
 */
float& SimOneDDS_Data_Control::brake()
{
    return m_brake;
}

/*!
 * @brief This function sets a value in member steeringMode
 * @param _steeringMode New value for member steeringMode
 */
void SimOneDDS_Data_Control::steeringMode(
        ESimOneDDS_Steering_Mode _steeringMode)
{
    m_steeringMode = _steeringMode;
}

/*!
 * @brief This function returns the value of member steeringMode
 * @return Value of member steeringMode
 */
ESimOneDDS_Steering_Mode SimOneDDS_Data_Control::steeringMode() const
{
    return m_steeringMode;
}

/*!
 * @brief This function returns a reference to member steeringMode
 * @return Reference to member steeringMode
 */
ESimOneDDS_Steering_Mode& SimOneDDS_Data_Control::steeringMode()
{
    return m_steeringMode;
}

/*!
 * @brief This function sets a value in member steering
 * @param _steering New value for member steering
 */
void SimOneDDS_Data_Control::steering(
        float _steering)
{
    m_steering = _steering;
}

/*!
 * @brief This function returns the value of member steering
 * @return Value of member steering
 */
float SimOneDDS_Data_Control::steering() const
{
    return m_steering;
}

/*!
 * @brief This function returns a reference to member steering
 * @return Reference to member steering
 */
float& SimOneDDS_Data_Control::steering()
{
    return m_steering;
}

/*!
 * @brief This function sets a value in member handbrake
 * @param _handbrake New value for member handbrake
 */
void SimOneDDS_Data_Control::handbrake(
        bool _handbrake)
{
    m_handbrake = _handbrake;
}

/*!
 * @brief This function returns the value of member handbrake
 * @return Value of member handbrake
 */
bool SimOneDDS_Data_Control::handbrake() const
{
    return m_handbrake;
}

/*!
 * @brief This function returns a reference to member handbrake
 * @return Reference to member handbrake
 */
bool& SimOneDDS_Data_Control::handbrake()
{
    return m_handbrake;
}

/*!
 * @brief This function sets a value in member isManualGear
 * @param _isManualGear New value for member isManualGear
 */
void SimOneDDS_Data_Control::isManualGear(
        bool _isManualGear)
{
    m_isManualGear = _isManualGear;
}

/*!
 * @brief This function returns the value of member isManualGear
 * @return Value of member isManualGear
 */
bool SimOneDDS_Data_Control::isManualGear() const
{
    return m_isManualGear;
}

/*!
 * @brief This function returns a reference to member isManualGear
 * @return Reference to member isManualGear
 */
bool& SimOneDDS_Data_Control::isManualGear()
{
    return m_isManualGear;
}

/*!
 * @brief This function sets a value in member gear
 * @param _gear New value for member gear
 */
void SimOneDDS_Data_Control::gear(
        ESimOneDDS_Gear_Mode _gear)
{
    m_gear = _gear;
}

/*!
 * @brief This function returns the value of member gear
 * @return Value of member gear
 */
ESimOneDDS_Gear_Mode SimOneDDS_Data_Control::gear() const
{
    return m_gear;
}

/*!
 * @brief This function returns a reference to member gear
 * @return Reference to member gear
 */
ESimOneDDS_Gear_Mode& SimOneDDS_Data_Control::gear()
{
    return m_gear;
}


size_t SimOneDDS_Data_Control::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t current_align = current_alignment;












    return current_align;
}

bool SimOneDDS_Data_Control::isKeyDefined()
{
    return false;
}

void SimOneDDS_Data_Control::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
             
}
