// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file SimOne_Data.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _FAST_DDS_GENERATED_SIMONE_DATA_H_
#define _FAST_DDS_GENERATED_SIMONE_DATA_H_


#include <fastrtps/utils/fixed_size_string.hpp>

#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(SimOne_Data_SOURCE)
#define SimOne_Data_DllAPI __declspec( dllexport )
#else
#define SimOne_Data_DllAPI __declspec( dllimport )
#endif // SimOne_Data_SOURCE
#else
#define SimOne_Data_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define SimOne_Data_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
} // namespace fastcdr
} // namespace eprosima


/*!
 * @brief This class represents the structure SimOneDDS_Data defined by the user in the IDL file.
 * @ingroup SIMONE_DATA
 */
class SimOneDDS_Data
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport SimOneDDS_Data();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~SimOneDDS_Data();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object SimOneDDS_Data that will be copied.
     */
    eProsima_user_DllExport SimOneDDS_Data(
            const SimOneDDS_Data& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object SimOneDDS_Data that will be copied.
     */
    eProsima_user_DllExport SimOneDDS_Data(
            SimOneDDS_Data&& x);

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object SimOneDDS_Data that will be copied.
     */
    eProsima_user_DllExport SimOneDDS_Data& operator =(
            const SimOneDDS_Data& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object SimOneDDS_Data that will be copied.
     */
    eProsima_user_DllExport SimOneDDS_Data& operator =(
            SimOneDDS_Data&& x);

    /*!
     * @brief Comparison operator.
     * @param x SimOneDDS_Data object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const SimOneDDS_Data& x) const;

    /*!
     * @brief Comparison operator.
     * @param x SimOneDDS_Data object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const SimOneDDS_Data& x) const;

    /*!
     * @brief This function sets a value in member timestamp
     * @param _timestamp New value for member timestamp
     */
    eProsima_user_DllExport void timestamp(
            int64_t _timestamp);

    /*!
     * @brief This function returns the value of member timestamp
     * @return Value of member timestamp
     */
    eProsima_user_DllExport int64_t timestamp() const;

    /*!
     * @brief This function returns a reference to member timestamp
     * @return Reference to member timestamp
     */
    eProsima_user_DllExport int64_t& timestamp();

    /*!
     * @brief This function sets a value in member frame
     * @param _frame New value for member frame
     */
    eProsima_user_DllExport void frame(
            int32_t _frame);

    /*!
     * @brief This function returns the value of member frame
     * @return Value of member frame
     */
    eProsima_user_DllExport int32_t frame() const;

    /*!
     * @brief This function returns a reference to member frame
     * @return Reference to member frame
     */
    eProsima_user_DllExport int32_t& frame();

    /*!
     * @brief This function sets a value in member version
     * @param _version New value for member version
     */
    eProsima_user_DllExport void version(
            int32_t _version);

    /*!
     * @brief This function returns the value of member version
     * @return Value of member version
     */
    eProsima_user_DllExport int32_t version() const;

    /*!
     * @brief This function returns a reference to member version
     * @return Reference to member version
     */
    eProsima_user_DllExport int32_t& version();


    /*!
     * @brief This function returns the maximum serialized size of an object
     * depending on the buffer alignment.
     * @param current_alignment Buffer alignment.
     * @return Maximum serialized size.
     */
    eProsima_user_DllExport static size_t getMaxCdrSerializedSize(
            size_t current_alignment = 0);

    /*!
     * @brief This function returns the serialized size of a data depending on the buffer alignment.
     * @param data Data which is calculated its serialized size.
     * @param current_alignment Buffer alignment.
     * @return Serialized size.
     */
    eProsima_user_DllExport static size_t getCdrSerializedSize(
            const SimOneDDS_Data& data,
            size_t current_alignment = 0);


    /*!
     * @brief This function serializes an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void serialize(
            eprosima::fastcdr::Cdr& cdr) const;

    /*!
     * @brief This function deserializes an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void deserialize(
            eprosima::fastcdr::Cdr& cdr);



    /*!
     * @brief This function returns the maximum serialized size of the Key of an object
     * depending on the buffer alignment.
     * @param current_alignment Buffer alignment.
     * @return Maximum serialized size.
     */
    eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(
            size_t current_alignment = 0);

    /*!
     * @brief This function tells you if the Key has been defined for this type
     */
    eProsima_user_DllExport static bool isKeyDefined();

    /*!
     * @brief This function serializes the key members of an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void serializeKey(
            eprosima::fastcdr::Cdr& cdr) const;

private:

    int64_t m_timestamp;
    int32_t m_frame;
    int32_t m_version;
};

#endif // _FAST_DDS_GENERATED_SIMONE_DATA_H_