// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file SimOne_Data_Control.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _FAST_DDS_GENERATED_SIMONE_DATA_CONTROL_H_
#define _FAST_DDS_GENERATED_SIMONE_DATA_CONTROL_H_


#include <fastrtps/utils/fixed_size_string.hpp>

#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(SimOne_Data_Control_SOURCE)
#define SimOne_Data_Control_DllAPI __declspec( dllexport )
#else
#define SimOne_Data_Control_DllAPI __declspec( dllimport )
#endif // SimOne_Data_Control_SOURCE
#else
#define SimOne_Data_Control_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define SimOne_Data_Control_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
} // namespace fastcdr
} // namespace eprosima


/*!
 * @brief This class represents the enumeration ESimOneDDS_Throttle_Mode defined by the user in the IDL file.
 * @ingroup SIMONE_DATA_CONTROL
 */
enum ESimOneDDS_Throttle_Mode : uint32_t
{
    ESimOneDDS_Throttle_Mode_Percent,
    ESimOneDDS_Throttle_Mode_Torque,
    ESimOneDDS_Throttle_Mode_Speed,
    ESimOneDDS_Throttle_Mode_Accel,
    ESimOneDDS_Throttle_Mode_EngineAV,
    ESimOneDDS_Throttle_Mode_WheelTorque
};
/*!
 * @brief This class represents the enumeration ESimOneDDS_Brake_Mode defined by the user in the IDL file.
 * @ingroup SIMONE_DATA_CONTROL
 */
enum ESimOneDDS_Brake_Mode : uint32_t
{
    ESimOneDDS_Brake_Mode_Percent,
    ESimOneDDS_Brake_Mode_MasterCylinderPressure,
    ESimOneDDS_Brake_Mode_PedalForce,
    ESimOneDDS_Brake_Mode_WheelCylinderPressure,
    ESimOneDDS_Brake_Mode_WheelTorque
};
/*!
 * @brief This class represents the enumeration ESimOneDDS_Steering_Mode defined by the user in the IDL file.
 * @ingroup SIMONE_DATA_CONTROL
 */
enum ESimOneDDS_Steering_Mode : uint32_t
{
    ESimOneDDS_Steering_Mode_Percent,
    ESimOneDDS_Steering_Mode_SteeringWheelAngle,
    ESimOneDDS_Steering_Mode_Torque,
    ESimOneDDS_Steering_Mode_AngularSpeed,
    ESimOneDDS_Steering_Mode_WheelAngle,
    ESimOneDDS_Steering_Mode_WheelAnglarSpeed
};
/*!
 * @brief This class represents the enumeration ESimOneDDS_Gear_Mode defined by the user in the IDL file.
 * @ingroup SIMONE_DATA_CONTROL
 */
enum ESimOneDDS_Gear_Mode : uint32_t
{
    ESimOneDDS_Gear_Mode_Neutral,
    ESimOneDDS_Gear_Mode_Drive,
    ESimOneDDS_Gear_Mode_Reverse,
    ESimOneDDS_Gear_Mode_Parking
};
/*!
 * @brief This class represents the structure SimOneDDS_Data_Control defined by the user in the IDL file.
 * @ingroup SIMONE_DATA_CONTROL
 */
class SimOneDDS_Data_Control
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport SimOneDDS_Data_Control();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~SimOneDDS_Data_Control();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object SimOneDDS_Data_Control that will be copied.
     */
    eProsima_user_DllExport SimOneDDS_Data_Control(
            const SimOneDDS_Data_Control& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object SimOneDDS_Data_Control that will be copied.
     */
    eProsima_user_DllExport SimOneDDS_Data_Control(
            SimOneDDS_Data_Control&& x);

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object SimOneDDS_Data_Control that will be copied.
     */
    eProsima_user_DllExport SimOneDDS_Data_Control& operator =(
            const SimOneDDS_Data_Control& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object SimOneDDS_Data_Control that will be copied.
     */
    eProsima_user_DllExport SimOneDDS_Data_Control& operator =(
            SimOneDDS_Data_Control&& x);

    /*!
     * @brief Comparison operator.
     * @param x SimOneDDS_Data_Control object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const SimOneDDS_Data_Control& x) const;

    /*!
     * @brief Comparison operator.
     * @param x SimOneDDS_Data_Control object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const SimOneDDS_Data_Control& x) const;

    /*!
     * @brief This function sets a value in member throttleMode
     * @param _throttleMode New value for member throttleMode
     */
    eProsima_user_DllExport void throttleMode(
            ESimOneDDS_Throttle_Mode _throttleMode);

    /*!
     * @brief This function returns the value of member throttleMode
     * @return Value of member throttleMode
     */
    eProsima_user_DllExport ESimOneDDS_Throttle_Mode throttleMode() const;

    /*!
     * @brief This function returns a reference to member throttleMode
     * @return Reference to member throttleMode
     */
    eProsima_user_DllExport ESimOneDDS_Throttle_Mode& throttleMode();

    /*!
     * @brief This function sets a value in member throttle
     * @param _throttle New value for member throttle
     */
    eProsima_user_DllExport void throttle(
            float _throttle);

    /*!
     * @brief This function returns the value of member throttle
     * @return Value of member throttle
     */
    eProsima_user_DllExport float throttle() const;

    /*!
     * @brief This function returns a reference to member throttle
     * @return Reference to member throttle
     */
    eProsima_user_DllExport float& throttle();

    /*!
     * @brief This function sets a value in member brakeMode
     * @param _brakeMode New value for member brakeMode
     */
    eProsima_user_DllExport void brakeMode(
            ESimOneDDS_Brake_Mode _brakeMode);

    /*!
     * @brief This function returns the value of member brakeMode
     * @return Value of member brakeMode
     */
    eProsima_user_DllExport ESimOneDDS_Brake_Mode brakeMode() const;

    /*!
     * @brief This function returns a reference to member brakeMode
     * @return Reference to member brakeMode
     */
    eProsima_user_DllExport ESimOneDDS_Brake_Mode& brakeMode();

    /*!
     * @brief This function sets a value in member brake
     * @param _brake New value for member brake
     */
    eProsima_user_DllExport void brake(
            float _brake);

    /*!
     * @brief This function returns the value of member brake
     * @return Value of member brake
     */
    eProsima_user_DllExport float brake() const;

    /*!
     * @brief This function returns a reference to member brake
     * @return Reference to member brake
     */
    eProsima_user_DllExport float& brake();

    /*!
     * @brief This function sets a value in member steeringMode
     * @param _steeringMode New value for member steeringMode
     */
    eProsima_user_DllExport void steeringMode(
            ESimOneDDS_Steering_Mode _steeringMode);

    /*!
     * @brief This function returns the value of member steeringMode
     * @return Value of member steeringMode
     */
    eProsima_user_DllExport ESimOneDDS_Steering_Mode steeringMode() const;

    /*!
     * @brief This function returns a reference to member steeringMode
     * @return Reference to member steeringMode
     */
    eProsima_user_DllExport ESimOneDDS_Steering_Mode& steeringMode();

    /*!
     * @brief This function sets a value in member steering
     * @param _steering New value for member steering
     */
    eProsima_user_DllExport void steering(
            float _steering);

    /*!
     * @brief This function returns the value of member steering
     * @return Value of member steering
     */
    eProsima_user_DllExport float steering() const;

    /*!
     * @brief This function returns a reference to member steering
     * @return Reference to member steering
     */
    eProsima_user_DllExport float& steering();

    /*!
     * @brief This function sets a value in member handbrake
     * @param _handbrake New value for member handbrake
     */
    eProsima_user_DllExport void handbrake(
            bool _handbrake);

    /*!
     * @brief This function returns the value of member handbrake
     * @return Value of member handbrake
     */
    eProsima_user_DllExport bool handbrake() const;

    /*!
     * @brief This function returns a reference to member handbrake
     * @return Reference to member handbrake
     */
    eProsima_user_DllExport bool& handbrake();

    /*!
     * @brief This function sets a value in member isManualGear
     * @param _isManualGear New value for member isManualGear
     */
    eProsima_user_DllExport void isManualGear(
            bool _isManualGear);

    /*!
     * @brief This function returns the value of member isManualGear
     * @return Value of member isManualGear
     */
    eProsima_user_DllExport bool isManualGear() const;

    /*!
     * @brief This function returns a reference to member isManualGear
     * @return Reference to member isManualGear
     */
    eProsima_user_DllExport bool& isManualGear();

    /*!
     * @brief This function sets a value in member gear
     * @param _gear New value for member gear
     */
    eProsima_user_DllExport void gear(
            ESimOneDDS_Gear_Mode _gear);

    /*!
     * @brief This function returns the value of member gear
     * @return Value of member gear
     */
    eProsima_user_DllExport ESimOneDDS_Gear_Mode gear() const;

    /*!
     * @brief This function returns a reference to member gear
     * @return Reference to member gear
     */
    eProsima_user_DllExport ESimOneDDS_Gear_Mode& gear();


    /*!
     * @brief This function returns the maximum serialized size of an object
     * depending on the buffer alignment.
     * @param current_alignment Buffer alignment.
     * @return Maximum serialized size.
     */
    eProsima_user_DllExport static size_t getMaxCdrSerializedSize(
            size_t current_alignment = 0);

    /*!
     * @brief This function returns the serialized size of a data depending on the buffer alignment.
     * @param data Data which is calculated its serialized size.
     * @param current_alignment Buffer alignment.
     * @return Serialized size.
     */
    eProsima_user_DllExport static size_t getCdrSerializedSize(
            const SimOneDDS_Data_Control& data,
            size_t current_alignment = 0);


    /*!
     * @brief This function serializes an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void serialize(
            eprosima::fastcdr::Cdr& cdr) const;

    /*!
     * @brief This function deserializes an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void deserialize(
            eprosima::fastcdr::Cdr& cdr);



    /*!
     * @brief This function returns the maximum serialized size of the Key of an object
     * depending on the buffer alignment.
     * @param current_alignment Buffer alignment.
     * @return Maximum serialized size.
     */
    eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(
            size_t current_alignment = 0);

    /*!
     * @brief This function tells you if the Key has been defined for this type
     */
    eProsima_user_DllExport static bool isKeyDefined();

    /*!
     * @brief This function serializes the key members of an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void serializeKey(
            eprosima::fastcdr::Cdr& cdr) const;

private:

    ESimOneDDS_Throttle_Mode m_throttleMode;
    float m_throttle;
    ESimOneDDS_Brake_Mode m_brakeMode;
    float m_brake;
    ESimOneDDS_Steering_Mode m_steeringMode;
    float m_steering;
    bool m_handbrake;
    bool m_isManualGear;
    ESimOneDDS_Gear_Mode m_gear;
};

#endif // _FAST_DDS_GENERATED_SIMONE_DATA_CONTROL_H_