// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file SimOne_Data_Gps.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "SimOne_Data_Gps.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

SimOneDDS_Data_Gps::SimOneDDS_Data_Gps()
{
    // m_posX com.eprosima.idl.parser.typecode.PrimitiveTypeCode@276438c9
    m_posX = 0.0;
    // m_posY com.eprosima.idl.parser.typecode.PrimitiveTypeCode@588df31b
    m_posY = 0.0;
    // m_posZ com.eprosima.idl.parser.typecode.PrimitiveTypeCode@33b37288
    m_posZ = 0.0;
    // m_oriX com.eprosima.idl.parser.typecode.PrimitiveTypeCode@77a57272
    m_oriX = 0.0;
    // m_oriY com.eprosima.idl.parser.typecode.PrimitiveTypeCode@7181ae3f
    m_oriY = 0.0;
    // m_oriZ com.eprosima.idl.parser.typecode.PrimitiveTypeCode@46238e3f
    m_oriZ = 0.0;
    // m_velX com.eprosima.idl.parser.typecode.PrimitiveTypeCode@6e2c9341
    m_velX = 0.0;
    // m_velY com.eprosima.idl.parser.typecode.PrimitiveTypeCode@32464a14
    m_velY = 0.0;
    // m_velZ com.eprosima.idl.parser.typecode.PrimitiveTypeCode@4e4aea35
    m_velZ = 0.0;
    // m_throttle com.eprosima.idl.parser.typecode.PrimitiveTypeCode@1442d7b5
    m_throttle = 0.0;
    // m_brake com.eprosima.idl.parser.typecode.PrimitiveTypeCode@1efee8e7
    m_brake = 0.0;
    // m_steering com.eprosima.idl.parser.typecode.PrimitiveTypeCode@1ee807c6
    m_steering = 0.0;
    // m_gear com.eprosima.idl.parser.typecode.PrimitiveTypeCode@76a4d6c
    m_gear = 0;
    // m_accelX com.eprosima.idl.parser.typecode.PrimitiveTypeCode@517cd4b
    m_accelX = 0.0;
    // m_accelY com.eprosima.idl.parser.typecode.PrimitiveTypeCode@6cc7b4de
    m_accelY = 0.0;
    // m_accelZ com.eprosima.idl.parser.typecode.PrimitiveTypeCode@5cdd8682
    m_accelZ = 0.0;
    // m_angVelX com.eprosima.idl.parser.typecode.PrimitiveTypeCode@17776a8
    m_angVelX = 0.0;
    // m_angVelY com.eprosima.idl.parser.typecode.PrimitiveTypeCode@69a10787
    m_angVelY = 0.0;
    // m_angVelZ com.eprosima.idl.parser.typecode.PrimitiveTypeCode@2d127a61
    m_angVelZ = 0.0;
    // m_wheelSpeedFL com.eprosima.idl.parser.typecode.PrimitiveTypeCode@2bbaf4f0
    m_wheelSpeedFL = 0.0;
    // m_wheelSpeedFR com.eprosima.idl.parser.typecode.PrimitiveTypeCode@11c20519
    m_wheelSpeedFR = 0.0;
    // m_wheelSpeedRL com.eprosima.idl.parser.typecode.PrimitiveTypeCode@70beb599
    m_wheelSpeedRL = 0.0;
    // m_wheelSpeedRR com.eprosima.idl.parser.typecode.PrimitiveTypeCode@4e41089d
    m_wheelSpeedRR = 0.0;
    // m_engineRpm com.eprosima.idl.parser.typecode.PrimitiveTypeCode@32a068d1
    m_engineRpm = 0.0;
    // m_odometer com.eprosima.idl.parser.typecode.PrimitiveTypeCode@33cb5951
    m_odometer = 0.0;

}

SimOneDDS_Data_Gps::~SimOneDDS_Data_Gps()
{

























}

SimOneDDS_Data_Gps::SimOneDDS_Data_Gps(
        const SimOneDDS_Data_Gps& x)
{
    m_posX = x.m_posX;
    m_posY = x.m_posY;
    m_posZ = x.m_posZ;
    m_oriX = x.m_oriX;
    m_oriY = x.m_oriY;
    m_oriZ = x.m_oriZ;
    m_velX = x.m_velX;
    m_velY = x.m_velY;
    m_velZ = x.m_velZ;
    m_throttle = x.m_throttle;
    m_brake = x.m_brake;
    m_steering = x.m_steering;
    m_gear = x.m_gear;
    m_accelX = x.m_accelX;
    m_accelY = x.m_accelY;
    m_accelZ = x.m_accelZ;
    m_angVelX = x.m_angVelX;
    m_angVelY = x.m_angVelY;
    m_angVelZ = x.m_angVelZ;
    m_wheelSpeedFL = x.m_wheelSpeedFL;
    m_wheelSpeedFR = x.m_wheelSpeedFR;
    m_wheelSpeedRL = x.m_wheelSpeedRL;
    m_wheelSpeedRR = x.m_wheelSpeedRR;
    m_engineRpm = x.m_engineRpm;
    m_odometer = x.m_odometer;
}

SimOneDDS_Data_Gps::SimOneDDS_Data_Gps(
        SimOneDDS_Data_Gps&& x)
{
    m_posX = x.m_posX;
    m_posY = x.m_posY;
    m_posZ = x.m_posZ;
    m_oriX = x.m_oriX;
    m_oriY = x.m_oriY;
    m_oriZ = x.m_oriZ;
    m_velX = x.m_velX;
    m_velY = x.m_velY;
    m_velZ = x.m_velZ;
    m_throttle = x.m_throttle;
    m_brake = x.m_brake;
    m_steering = x.m_steering;
    m_gear = x.m_gear;
    m_accelX = x.m_accelX;
    m_accelY = x.m_accelY;
    m_accelZ = x.m_accelZ;
    m_angVelX = x.m_angVelX;
    m_angVelY = x.m_angVelY;
    m_angVelZ = x.m_angVelZ;
    m_wheelSpeedFL = x.m_wheelSpeedFL;
    m_wheelSpeedFR = x.m_wheelSpeedFR;
    m_wheelSpeedRL = x.m_wheelSpeedRL;
    m_wheelSpeedRR = x.m_wheelSpeedRR;
    m_engineRpm = x.m_engineRpm;
    m_odometer = x.m_odometer;
}

SimOneDDS_Data_Gps& SimOneDDS_Data_Gps::operator =(
        const SimOneDDS_Data_Gps& x)
{

    m_posX = x.m_posX;
    m_posY = x.m_posY;
    m_posZ = x.m_posZ;
    m_oriX = x.m_oriX;
    m_oriY = x.m_oriY;
    m_oriZ = x.m_oriZ;
    m_velX = x.m_velX;
    m_velY = x.m_velY;
    m_velZ = x.m_velZ;
    m_throttle = x.m_throttle;
    m_brake = x.m_brake;
    m_steering = x.m_steering;
    m_gear = x.m_gear;
    m_accelX = x.m_accelX;
    m_accelY = x.m_accelY;
    m_accelZ = x.m_accelZ;
    m_angVelX = x.m_angVelX;
    m_angVelY = x.m_angVelY;
    m_angVelZ = x.m_angVelZ;
    m_wheelSpeedFL = x.m_wheelSpeedFL;
    m_wheelSpeedFR = x.m_wheelSpeedFR;
    m_wheelSpeedRL = x.m_wheelSpeedRL;
    m_wheelSpeedRR = x.m_wheelSpeedRR;
    m_engineRpm = x.m_engineRpm;
    m_odometer = x.m_odometer;

    return *this;
}

SimOneDDS_Data_Gps& SimOneDDS_Data_Gps::operator =(
        SimOneDDS_Data_Gps&& x)
{

    m_posX = x.m_posX;
    m_posY = x.m_posY;
    m_posZ = x.m_posZ;
    m_oriX = x.m_oriX;
    m_oriY = x.m_oriY;
    m_oriZ = x.m_oriZ;
    m_velX = x.m_velX;
    m_velY = x.m_velY;
    m_velZ = x.m_velZ;
    m_throttle = x.m_throttle;
    m_brake = x.m_brake;
    m_steering = x.m_steering;
    m_gear = x.m_gear;
    m_accelX = x.m_accelX;
    m_accelY = x.m_accelY;
    m_accelZ = x.m_accelZ;
    m_angVelX = x.m_angVelX;
    m_angVelY = x.m_angVelY;
    m_angVelZ = x.m_angVelZ;
    m_wheelSpeedFL = x.m_wheelSpeedFL;
    m_wheelSpeedFR = x.m_wheelSpeedFR;
    m_wheelSpeedRL = x.m_wheelSpeedRL;
    m_wheelSpeedRR = x.m_wheelSpeedRR;
    m_engineRpm = x.m_engineRpm;
    m_odometer = x.m_odometer;

    return *this;
}

bool SimOneDDS_Data_Gps::operator ==(
        const SimOneDDS_Data_Gps& x) const
{

    return (m_posX == x.m_posX && m_posY == x.m_posY && m_posZ == x.m_posZ && m_oriX == x.m_oriX && m_oriY == x.m_oriY && m_oriZ == x.m_oriZ && m_velX == x.m_velX && m_velY == x.m_velY && m_velZ == x.m_velZ && m_throttle == x.m_throttle && m_brake == x.m_brake && m_steering == x.m_steering && m_gear == x.m_gear && m_accelX == x.m_accelX && m_accelY == x.m_accelY && m_accelZ == x.m_accelZ && m_angVelX == x.m_angVelX && m_angVelY == x.m_angVelY && m_angVelZ == x.m_angVelZ && m_wheelSpeedFL == x.m_wheelSpeedFL && m_wheelSpeedFR == x.m_wheelSpeedFR && m_wheelSpeedRL == x.m_wheelSpeedRL && m_wheelSpeedRR == x.m_wheelSpeedRR && m_engineRpm == x.m_engineRpm && m_odometer == x.m_odometer);
}

bool SimOneDDS_Data_Gps::operator !=(
        const SimOneDDS_Data_Gps& x) const
{
    return !(*this == x);
}

size_t SimOneDDS_Data_Gps::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);



    return current_alignment - initial_alignment;
}

size_t SimOneDDS_Data_Gps::getCdrSerializedSize(
        const SimOneDDS_Data_Gps& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);



    return current_alignment - initial_alignment;
}

void SimOneDDS_Data_Gps::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_posX;
    scdr << m_posY;
    scdr << m_posZ;
    scdr << m_oriX;
    scdr << m_oriY;
    scdr << m_oriZ;
    scdr << m_velX;
    scdr << m_velY;
    scdr << m_velZ;
    scdr << m_throttle;
    scdr << m_brake;
    scdr << m_steering;
    scdr << m_gear;
    scdr << m_accelX;
    scdr << m_accelY;
    scdr << m_accelZ;
    scdr << m_angVelX;
    scdr << m_angVelY;
    scdr << m_angVelZ;
    scdr << m_wheelSpeedFL;
    scdr << m_wheelSpeedFR;
    scdr << m_wheelSpeedRL;
    scdr << m_wheelSpeedRR;
    scdr << m_engineRpm;
    scdr << m_odometer;

}

void SimOneDDS_Data_Gps::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_posX;
    dcdr >> m_posY;
    dcdr >> m_posZ;
    dcdr >> m_oriX;
    dcdr >> m_oriY;
    dcdr >> m_oriZ;
    dcdr >> m_velX;
    dcdr >> m_velY;
    dcdr >> m_velZ;
    dcdr >> m_throttle;
    dcdr >> m_brake;
    dcdr >> m_steering;
    dcdr >> m_gear;
    dcdr >> m_accelX;
    dcdr >> m_accelY;
    dcdr >> m_accelZ;
    dcdr >> m_angVelX;
    dcdr >> m_angVelY;
    dcdr >> m_angVelZ;
    dcdr >> m_wheelSpeedFL;
    dcdr >> m_wheelSpeedFR;
    dcdr >> m_wheelSpeedRL;
    dcdr >> m_wheelSpeedRR;
    dcdr >> m_engineRpm;
    dcdr >> m_odometer;
}

/*!
 * @brief This function sets a value in member posX
 * @param _posX New value for member posX
 */
void SimOneDDS_Data_Gps::posX(
        float _posX)
{
    m_posX = _posX;
}

/*!
 * @brief This function returns the value of member posX
 * @return Value of member posX
 */
float SimOneDDS_Data_Gps::posX() const
{
    return m_posX;
}

/*!
 * @brief This function returns a reference to member posX
 * @return Reference to member posX
 */
float& SimOneDDS_Data_Gps::posX()
{
    return m_posX;
}

/*!
 * @brief This function sets a value in member posY
 * @param _posY New value for member posY
 */
void SimOneDDS_Data_Gps::posY(
        float _posY)
{
    m_posY = _posY;
}

/*!
 * @brief This function returns the value of member posY
 * @return Value of member posY
 */
float SimOneDDS_Data_Gps::posY() const
{
    return m_posY;
}

/*!
 * @brief This function returns a reference to member posY
 * @return Reference to member posY
 */
float& SimOneDDS_Data_Gps::posY()
{
    return m_posY;
}

/*!
 * @brief This function sets a value in member posZ
 * @param _posZ New value for member posZ
 */
void SimOneDDS_Data_Gps::posZ(
        float _posZ)
{
    m_posZ = _posZ;
}

/*!
 * @brief This function returns the value of member posZ
 * @return Value of member posZ
 */
float SimOneDDS_Data_Gps::posZ() const
{
    return m_posZ;
}

/*!
 * @brief This function returns a reference to member posZ
 * @return Reference to member posZ
 */
float& SimOneDDS_Data_Gps::posZ()
{
    return m_posZ;
}

/*!
 * @brief This function sets a value in member oriX
 * @param _oriX New value for member oriX
 */
void SimOneDDS_Data_Gps::oriX(
        float _oriX)
{
    m_oriX = _oriX;
}

/*!
 * @brief This function returns the value of member oriX
 * @return Value of member oriX
 */
float SimOneDDS_Data_Gps::oriX() const
{
    return m_oriX;
}

/*!
 * @brief This function returns a reference to member oriX
 * @return Reference to member oriX
 */
float& SimOneDDS_Data_Gps::oriX()
{
    return m_oriX;
}

/*!
 * @brief This function sets a value in member oriY
 * @param _oriY New value for member oriY
 */
void SimOneDDS_Data_Gps::oriY(
        float _oriY)
{
    m_oriY = _oriY;
}

/*!
 * @brief This function returns the value of member oriY
 * @return Value of member oriY
 */
float SimOneDDS_Data_Gps::oriY() const
{
    return m_oriY;
}

/*!
 * @brief This function returns a reference to member oriY
 * @return Reference to member oriY
 */
float& SimOneDDS_Data_Gps::oriY()
{
    return m_oriY;
}

/*!
 * @brief This function sets a value in member oriZ
 * @param _oriZ New value for member oriZ
 */
void SimOneDDS_Data_Gps::oriZ(
        float _oriZ)
{
    m_oriZ = _oriZ;
}

/*!
 * @brief This function returns the value of member oriZ
 * @return Value of member oriZ
 */
float SimOneDDS_Data_Gps::oriZ() const
{
    return m_oriZ;
}

/*!
 * @brief This function returns a reference to member oriZ
 * @return Reference to member oriZ
 */
float& SimOneDDS_Data_Gps::oriZ()
{
    return m_oriZ;
}

/*!
 * @brief This function sets a value in member velX
 * @param _velX New value for member velX
 */
void SimOneDDS_Data_Gps::velX(
        float _velX)
{
    m_velX = _velX;
}

/*!
 * @brief This function returns the value of member velX
 * @return Value of member velX
 */
float SimOneDDS_Data_Gps::velX() const
{
    return m_velX;
}

/*!
 * @brief This function returns a reference to member velX
 * @return Reference to member velX
 */
float& SimOneDDS_Data_Gps::velX()
{
    return m_velX;
}

/*!
 * @brief This function sets a value in member velY
 * @param _velY New value for member velY
 */
void SimOneDDS_Data_Gps::velY(
        float _velY)
{
    m_velY = _velY;
}

/*!
 * @brief This function returns the value of member velY
 * @return Value of member velY
 */
float SimOneDDS_Data_Gps::velY() const
{
    return m_velY;
}

/*!
 * @brief This function returns a reference to member velY
 * @return Reference to member velY
 */
float& SimOneDDS_Data_Gps::velY()
{
    return m_velY;
}

/*!
 * @brief This function sets a value in member velZ
 * @param _velZ New value for member velZ
 */
void SimOneDDS_Data_Gps::velZ(
        float _velZ)
{
    m_velZ = _velZ;
}

/*!
 * @brief This function returns the value of member velZ
 * @return Value of member velZ
 */
float SimOneDDS_Data_Gps::velZ() const
{
    return m_velZ;
}

/*!
 * @brief This function returns a reference to member velZ
 * @return Reference to member velZ
 */
float& SimOneDDS_Data_Gps::velZ()
{
    return m_velZ;
}

/*!
 * @brief This function sets a value in member throttle
 * @param _throttle New value for member throttle
 */
void SimOneDDS_Data_Gps::throttle(
        float _throttle)
{
    m_throttle = _throttle;
}

/*!
 * @brief This function returns the value of member throttle
 * @return Value of member throttle
 */
float SimOneDDS_Data_Gps::throttle() const
{
    return m_throttle;
}

/*!
 * @brief This function returns a reference to member throttle
 * @return Reference to member throttle
 */
float& SimOneDDS_Data_Gps::throttle()
{
    return m_throttle;
}

/*!
 * @brief This function sets a value in member brake
 * @param _brake New value for member brake
 */
void SimOneDDS_Data_Gps::brake(
        float _brake)
{
    m_brake = _brake;
}

/*!
 * @brief This function returns the value of member brake
 * @return Value of member brake
 */
float SimOneDDS_Data_Gps::brake() const
{
    return m_brake;
}

/*!
 * @brief This function returns a reference to member brake
 * @return Reference to member brake
 */
float& SimOneDDS_Data_Gps::brake()
{
    return m_brake;
}

/*!
 * @brief This function sets a value in member steering
 * @param _steering New value for member steering
 */
void SimOneDDS_Data_Gps::steering(
        float _steering)
{
    m_steering = _steering;
}

/*!
 * @brief This function returns the value of member steering
 * @return Value of member steering
 */
float SimOneDDS_Data_Gps::steering() const
{
    return m_steering;
}

/*!
 * @brief This function returns a reference to member steering
 * @return Reference to member steering
 */
float& SimOneDDS_Data_Gps::steering()
{
    return m_steering;
}

/*!
 * @brief This function sets a value in member gear
 * @param _gear New value for member gear
 */
void SimOneDDS_Data_Gps::gear(
        int32_t _gear)
{
    m_gear = _gear;
}

/*!
 * @brief This function returns the value of member gear
 * @return Value of member gear
 */
int32_t SimOneDDS_Data_Gps::gear() const
{
    return m_gear;
}

/*!
 * @brief This function returns a reference to member gear
 * @return Reference to member gear
 */
int32_t& SimOneDDS_Data_Gps::gear()
{
    return m_gear;
}

/*!
 * @brief This function sets a value in member accelX
 * @param _accelX New value for member accelX
 */
void SimOneDDS_Data_Gps::accelX(
        float _accelX)
{
    m_accelX = _accelX;
}

/*!
 * @brief This function returns the value of member accelX
 * @return Value of member accelX
 */
float SimOneDDS_Data_Gps::accelX() const
{
    return m_accelX;
}

/*!
 * @brief This function returns a reference to member accelX
 * @return Reference to member accelX
 */
float& SimOneDDS_Data_Gps::accelX()
{
    return m_accelX;
}

/*!
 * @brief This function sets a value in member accelY
 * @param _accelY New value for member accelY
 */
void SimOneDDS_Data_Gps::accelY(
        float _accelY)
{
    m_accelY = _accelY;
}

/*!
 * @brief This function returns the value of member accelY
 * @return Value of member accelY
 */
float SimOneDDS_Data_Gps::accelY() const
{
    return m_accelY;
}

/*!
 * @brief This function returns a reference to member accelY
 * @return Reference to member accelY
 */
float& SimOneDDS_Data_Gps::accelY()
{
    return m_accelY;
}

/*!
 * @brief This function sets a value in member accelZ
 * @param _accelZ New value for member accelZ
 */
void SimOneDDS_Data_Gps::accelZ(
        float _accelZ)
{
    m_accelZ = _accelZ;
}

/*!
 * @brief This function returns the value of member accelZ
 * @return Value of member accelZ
 */
float SimOneDDS_Data_Gps::accelZ() const
{
    return m_accelZ;
}

/*!
 * @brief This function returns a reference to member accelZ
 * @return Reference to member accelZ
 */
float& SimOneDDS_Data_Gps::accelZ()
{
    return m_accelZ;
}

/*!
 * @brief This function sets a value in member angVelX
 * @param _angVelX New value for member angVelX
 */
void SimOneDDS_Data_Gps::angVelX(
        float _angVelX)
{
    m_angVelX = _angVelX;
}

/*!
 * @brief This function returns the value of member angVelX
 * @return Value of member angVelX
 */
float SimOneDDS_Data_Gps::angVelX() const
{
    return m_angVelX;
}

/*!
 * @brief This function returns a reference to member angVelX
 * @return Reference to member angVelX
 */
float& SimOneDDS_Data_Gps::angVelX()
{
    return m_angVelX;
}

/*!
 * @brief This function sets a value in member angVelY
 * @param _angVelY New value for member angVelY
 */
void SimOneDDS_Data_Gps::angVelY(
        float _angVelY)
{
    m_angVelY = _angVelY;
}

/*!
 * @brief This function returns the value of member angVelY
 * @return Value of member angVelY
 */
float SimOneDDS_Data_Gps::angVelY() const
{
    return m_angVelY;
}

/*!
 * @brief This function returns a reference to member angVelY
 * @return Reference to member angVelY
 */
float& SimOneDDS_Data_Gps::angVelY()
{
    return m_angVelY;
}

/*!
 * @brief This function sets a value in member angVelZ
 * @param _angVelZ New value for member angVelZ
 */
void SimOneDDS_Data_Gps::angVelZ(
        float _angVelZ)
{
    m_angVelZ = _angVelZ;
}

/*!
 * @brief This function returns the value of member angVelZ
 * @return Value of member angVelZ
 */
float SimOneDDS_Data_Gps::angVelZ() const
{
    return m_angVelZ;
}

/*!
 * @brief This function returns a reference to member angVelZ
 * @return Reference to member angVelZ
 */
float& SimOneDDS_Data_Gps::angVelZ()
{
    return m_angVelZ;
}

/*!
 * @brief This function sets a value in member wheelSpeedFL
 * @param _wheelSpeedFL New value for member wheelSpeedFL
 */
void SimOneDDS_Data_Gps::wheelSpeedFL(
        float _wheelSpeedFL)
{
    m_wheelSpeedFL = _wheelSpeedFL;
}

/*!
 * @brief This function returns the value of member wheelSpeedFL
 * @return Value of member wheelSpeedFL
 */
float SimOneDDS_Data_Gps::wheelSpeedFL() const
{
    return m_wheelSpeedFL;
}

/*!
 * @brief This function returns a reference to member wheelSpeedFL
 * @return Reference to member wheelSpeedFL
 */
float& SimOneDDS_Data_Gps::wheelSpeedFL()
{
    return m_wheelSpeedFL;
}

/*!
 * @brief This function sets a value in member wheelSpeedFR
 * @param _wheelSpeedFR New value for member wheelSpeedFR
 */
void SimOneDDS_Data_Gps::wheelSpeedFR(
        float _wheelSpeedFR)
{
    m_wheelSpeedFR = _wheelSpeedFR;
}

/*!
 * @brief This function returns the value of member wheelSpeedFR
 * @return Value of member wheelSpeedFR
 */
float SimOneDDS_Data_Gps::wheelSpeedFR() const
{
    return m_wheelSpeedFR;
}

/*!
 * @brief This function returns a reference to member wheelSpeedFR
 * @return Reference to member wheelSpeedFR
 */
float& SimOneDDS_Data_Gps::wheelSpeedFR()
{
    return m_wheelSpeedFR;
}

/*!
 * @brief This function sets a value in member wheelSpeedRL
 * @param _wheelSpeedRL New value for member wheelSpeedRL
 */
void SimOneDDS_Data_Gps::wheelSpeedRL(
        float _wheelSpeedRL)
{
    m_wheelSpeedRL = _wheelSpeedRL;
}

/*!
 * @brief This function returns the value of member wheelSpeedRL
 * @return Value of member wheelSpeedRL
 */
float SimOneDDS_Data_Gps::wheelSpeedRL() const
{
    return m_wheelSpeedRL;
}

/*!
 * @brief This function returns a reference to member wheelSpeedRL
 * @return Reference to member wheelSpeedRL
 */
float& SimOneDDS_Data_Gps::wheelSpeedRL()
{
    return m_wheelSpeedRL;
}

/*!
 * @brief This function sets a value in member wheelSpeedRR
 * @param _wheelSpeedRR New value for member wheelSpeedRR
 */
void SimOneDDS_Data_Gps::wheelSpeedRR(
        float _wheelSpeedRR)
{
    m_wheelSpeedRR = _wheelSpeedRR;
}

/*!
 * @brief This function returns the value of member wheelSpeedRR
 * @return Value of member wheelSpeedRR
 */
float SimOneDDS_Data_Gps::wheelSpeedRR() const
{
    return m_wheelSpeedRR;
}

/*!
 * @brief This function returns a reference to member wheelSpeedRR
 * @return Reference to member wheelSpeedRR
 */
float& SimOneDDS_Data_Gps::wheelSpeedRR()
{
    return m_wheelSpeedRR;
}

/*!
 * @brief This function sets a value in member engineRpm
 * @param _engineRpm New value for member engineRpm
 */
void SimOneDDS_Data_Gps::engineRpm(
        float _engineRpm)
{
    m_engineRpm = _engineRpm;
}

/*!
 * @brief This function returns the value of member engineRpm
 * @return Value of member engineRpm
 */
float SimOneDDS_Data_Gps::engineRpm() const
{
    return m_engineRpm;
}

/*!
 * @brief This function returns a reference to member engineRpm
 * @return Reference to member engineRpm
 */
float& SimOneDDS_Data_Gps::engineRpm()
{
    return m_engineRpm;
}

/*!
 * @brief This function sets a value in member odometer
 * @param _odometer New value for member odometer
 */
void SimOneDDS_Data_Gps::odometer(
        float _odometer)
{
    m_odometer = _odometer;
}

/*!
 * @brief This function returns the value of member odometer
 * @return Value of member odometer
 */
float SimOneDDS_Data_Gps::odometer() const
{
    return m_odometer;
}

/*!
 * @brief This function returns a reference to member odometer
 * @return Reference to member odometer
 */
float& SimOneDDS_Data_Gps::odometer()
{
    return m_odometer;
}


size_t SimOneDDS_Data_Gps::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t current_align = current_alignment;




























    return current_align;
}

bool SimOneDDS_Data_Gps::isKeyDefined()
{
    return false;
}

void SimOneDDS_Data_Gps::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
                             
}
