// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file SimOne_Data_Obstacle.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "SimOne_Data_Obstacle.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>


SimOneDDS_Data_Obstacle_Entry::SimOneDDS_Data_Obstacle_Entry()
{
    // m_id com.eprosima.idl.parser.typecode.PrimitiveTypeCode@77a57272
    m_id = 0;
    // m_viewId com.eprosima.idl.parser.typecode.PrimitiveTypeCode@7181ae3f
    m_viewId = 0;
    // m_type com.eprosima.idl.parser.typecode.EnumTypeCode@46238e3f
    m_type = ::ESimOneDDS_Obstacle_Type_Unknown;
    // m_theta com.eprosima.idl.parser.typecode.PrimitiveTypeCode@6e2c9341
    m_theta = 0.0;
    // m_posX com.eprosima.idl.parser.typecode.PrimitiveTypeCode@32464a14
    m_posX = 0.0;
    // m_posY com.eprosima.idl.parser.typecode.PrimitiveTypeCode@4e4aea35
    m_posY = 0.0;
    // m_posZ com.eprosima.idl.parser.typecode.PrimitiveTypeCode@1442d7b5
    m_posZ = 0.0;
    // m_oriX com.eprosima.idl.parser.typecode.PrimitiveTypeCode@1efee8e7
    m_oriX = 0.0;
    // m_oriY com.eprosima.idl.parser.typecode.PrimitiveTypeCode@1ee807c6
    m_oriY = 0.0;
    // m_oriZ com.eprosima.idl.parser.typecode.PrimitiveTypeCode@76a4d6c
    m_oriZ = 0.0;
    // m_velX com.eprosima.idl.parser.typecode.PrimitiveTypeCode@517cd4b
    m_velX = 0.0;
    // m_velY com.eprosima.idl.parser.typecode.PrimitiveTypeCode@6cc7b4de
    m_velY = 0.0;
    // m_velZ com.eprosima.idl.parser.typecode.PrimitiveTypeCode@32cf48b7
    m_velZ = 0.0;
    // m_length com.eprosima.idl.parser.typecode.PrimitiveTypeCode@679b62af
    m_length = 0.0;
    // m_width com.eprosima.idl.parser.typecode.PrimitiveTypeCode@5cdd8682
    m_width = 0.0;
    // m_height com.eprosima.idl.parser.typecode.PrimitiveTypeCode@799d4f69
    m_height = 0.0;
    // m_accelX com.eprosima.idl.parser.typecode.PrimitiveTypeCode@69a10787
    m_accelX = 0.0;
    // m_accelY com.eprosima.idl.parser.typecode.PrimitiveTypeCode@11c20519
    m_accelY = 0.0;
    // m_accelZ com.eprosima.idl.parser.typecode.PrimitiveTypeCode@70beb599
    m_accelZ = 0.0;

}

SimOneDDS_Data_Obstacle_Entry::~SimOneDDS_Data_Obstacle_Entry()
{



















}

SimOneDDS_Data_Obstacle_Entry::SimOneDDS_Data_Obstacle_Entry(
        const SimOneDDS_Data_Obstacle_Entry& x)
{
    m_id = x.m_id;
    m_viewId = x.m_viewId;
    m_type = x.m_type;
    m_theta = x.m_theta;
    m_posX = x.m_posX;
    m_posY = x.m_posY;
    m_posZ = x.m_posZ;
    m_oriX = x.m_oriX;
    m_oriY = x.m_oriY;
    m_oriZ = x.m_oriZ;
    m_velX = x.m_velX;
    m_velY = x.m_velY;
    m_velZ = x.m_velZ;
    m_length = x.m_length;
    m_width = x.m_width;
    m_height = x.m_height;
    m_accelX = x.m_accelX;
    m_accelY = x.m_accelY;
    m_accelZ = x.m_accelZ;
}

SimOneDDS_Data_Obstacle_Entry::SimOneDDS_Data_Obstacle_Entry(
        SimOneDDS_Data_Obstacle_Entry&& x)
{
    m_id = x.m_id;
    m_viewId = x.m_viewId;
    m_type = x.m_type;
    m_theta = x.m_theta;
    m_posX = x.m_posX;
    m_posY = x.m_posY;
    m_posZ = x.m_posZ;
    m_oriX = x.m_oriX;
    m_oriY = x.m_oriY;
    m_oriZ = x.m_oriZ;
    m_velX = x.m_velX;
    m_velY = x.m_velY;
    m_velZ = x.m_velZ;
    m_length = x.m_length;
    m_width = x.m_width;
    m_height = x.m_height;
    m_accelX = x.m_accelX;
    m_accelY = x.m_accelY;
    m_accelZ = x.m_accelZ;
}

SimOneDDS_Data_Obstacle_Entry& SimOneDDS_Data_Obstacle_Entry::operator =(
        const SimOneDDS_Data_Obstacle_Entry& x)
{

    m_id = x.m_id;
    m_viewId = x.m_viewId;
    m_type = x.m_type;
    m_theta = x.m_theta;
    m_posX = x.m_posX;
    m_posY = x.m_posY;
    m_posZ = x.m_posZ;
    m_oriX = x.m_oriX;
    m_oriY = x.m_oriY;
    m_oriZ = x.m_oriZ;
    m_velX = x.m_velX;
    m_velY = x.m_velY;
    m_velZ = x.m_velZ;
    m_length = x.m_length;
    m_width = x.m_width;
    m_height = x.m_height;
    m_accelX = x.m_accelX;
    m_accelY = x.m_accelY;
    m_accelZ = x.m_accelZ;

    return *this;
}

SimOneDDS_Data_Obstacle_Entry& SimOneDDS_Data_Obstacle_Entry::operator =(
        SimOneDDS_Data_Obstacle_Entry&& x)
{

    m_id = x.m_id;
    m_viewId = x.m_viewId;
    m_type = x.m_type;
    m_theta = x.m_theta;
    m_posX = x.m_posX;
    m_posY = x.m_posY;
    m_posZ = x.m_posZ;
    m_oriX = x.m_oriX;
    m_oriY = x.m_oriY;
    m_oriZ = x.m_oriZ;
    m_velX = x.m_velX;
    m_velY = x.m_velY;
    m_velZ = x.m_velZ;
    m_length = x.m_length;
    m_width = x.m_width;
    m_height = x.m_height;
    m_accelX = x.m_accelX;
    m_accelY = x.m_accelY;
    m_accelZ = x.m_accelZ;

    return *this;
}

bool SimOneDDS_Data_Obstacle_Entry::operator ==(
        const SimOneDDS_Data_Obstacle_Entry& x) const
{

    return (m_id == x.m_id && m_viewId == x.m_viewId && m_type == x.m_type && m_theta == x.m_theta && m_posX == x.m_posX && m_posY == x.m_posY && m_posZ == x.m_posZ && m_oriX == x.m_oriX && m_oriY == x.m_oriY && m_oriZ == x.m_oriZ && m_velX == x.m_velX && m_velY == x.m_velY && m_velZ == x.m_velZ && m_length == x.m_length && m_width == x.m_width && m_height == x.m_height && m_accelX == x.m_accelX && m_accelY == x.m_accelY && m_accelZ == x.m_accelZ);
}

bool SimOneDDS_Data_Obstacle_Entry::operator !=(
        const SimOneDDS_Data_Obstacle_Entry& x) const
{
    return !(*this == x);
}

size_t SimOneDDS_Data_Obstacle_Entry::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);



    return current_alignment - initial_alignment;
}

size_t SimOneDDS_Data_Obstacle_Entry::getCdrSerializedSize(
        const SimOneDDS_Data_Obstacle_Entry& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);



    return current_alignment - initial_alignment;
}

void SimOneDDS_Data_Obstacle_Entry::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_id;
    scdr << m_viewId;
    scdr << (uint32_t)m_type;
    scdr << m_theta;
    scdr << m_posX;
    scdr << m_posY;
    scdr << m_posZ;
    scdr << m_oriX;
    scdr << m_oriY;
    scdr << m_oriZ;
    scdr << m_velX;
    scdr << m_velY;
    scdr << m_velZ;
    scdr << m_length;
    scdr << m_width;
    scdr << m_height;
    scdr << m_accelX;
    scdr << m_accelY;
    scdr << m_accelZ;

}

void SimOneDDS_Data_Obstacle_Entry::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_id;
    dcdr >> m_viewId;
    {
        uint32_t enum_value = 0;
        dcdr >> enum_value;
        m_type = (ESimOneDDS_Obstacle_Type)enum_value;
    }

    dcdr >> m_theta;
    dcdr >> m_posX;
    dcdr >> m_posY;
    dcdr >> m_posZ;
    dcdr >> m_oriX;
    dcdr >> m_oriY;
    dcdr >> m_oriZ;
    dcdr >> m_velX;
    dcdr >> m_velY;
    dcdr >> m_velZ;
    dcdr >> m_length;
    dcdr >> m_width;
    dcdr >> m_height;
    dcdr >> m_accelX;
    dcdr >> m_accelY;
    dcdr >> m_accelZ;
}

/*!
 * @brief This function sets a value in member id
 * @param _id New value for member id
 */
void SimOneDDS_Data_Obstacle_Entry::id(
        int32_t _id)
{
    m_id = _id;
}

/*!
 * @brief This function returns the value of member id
 * @return Value of member id
 */
int32_t SimOneDDS_Data_Obstacle_Entry::id() const
{
    return m_id;
}

/*!
 * @brief This function returns a reference to member id
 * @return Reference to member id
 */
int32_t& SimOneDDS_Data_Obstacle_Entry::id()
{
    return m_id;
}

/*!
 * @brief This function sets a value in member viewId
 * @param _viewId New value for member viewId
 */
void SimOneDDS_Data_Obstacle_Entry::viewId(
        int32_t _viewId)
{
    m_viewId = _viewId;
}

/*!
 * @brief This function returns the value of member viewId
 * @return Value of member viewId
 */
int32_t SimOneDDS_Data_Obstacle_Entry::viewId() const
{
    return m_viewId;
}

/*!
 * @brief This function returns a reference to member viewId
 * @return Reference to member viewId
 */
int32_t& SimOneDDS_Data_Obstacle_Entry::viewId()
{
    return m_viewId;
}

/*!
 * @brief This function sets a value in member type
 * @param _type New value for member type
 */
void SimOneDDS_Data_Obstacle_Entry::type(
        ESimOneDDS_Obstacle_Type _type)
{
    m_type = _type;
}

/*!
 * @brief This function returns the value of member type
 * @return Value of member type
 */
ESimOneDDS_Obstacle_Type SimOneDDS_Data_Obstacle_Entry::type() const
{
    return m_type;
}

/*!
 * @brief This function returns a reference to member type
 * @return Reference to member type
 */
ESimOneDDS_Obstacle_Type& SimOneDDS_Data_Obstacle_Entry::type()
{
    return m_type;
}

/*!
 * @brief This function sets a value in member theta
 * @param _theta New value for member theta
 */
void SimOneDDS_Data_Obstacle_Entry::theta(
        float _theta)
{
    m_theta = _theta;
}

/*!
 * @brief This function returns the value of member theta
 * @return Value of member theta
 */
float SimOneDDS_Data_Obstacle_Entry::theta() const
{
    return m_theta;
}

/*!
 * @brief This function returns a reference to member theta
 * @return Reference to member theta
 */
float& SimOneDDS_Data_Obstacle_Entry::theta()
{
    return m_theta;
}

/*!
 * @brief This function sets a value in member posX
 * @param _posX New value for member posX
 */
void SimOneDDS_Data_Obstacle_Entry::posX(
        float _posX)
{
    m_posX = _posX;
}

/*!
 * @brief This function returns the value of member posX
 * @return Value of member posX
 */
float SimOneDDS_Data_Obstacle_Entry::posX() const
{
    return m_posX;
}

/*!
 * @brief This function returns a reference to member posX
 * @return Reference to member posX
 */
float& SimOneDDS_Data_Obstacle_Entry::posX()
{
    return m_posX;
}

/*!
 * @brief This function sets a value in member posY
 * @param _posY New value for member posY
 */
void SimOneDDS_Data_Obstacle_Entry::posY(
        float _posY)
{
    m_posY = _posY;
}

/*!
 * @brief This function returns the value of member posY
 * @return Value of member posY
 */
float SimOneDDS_Data_Obstacle_Entry::posY() const
{
    return m_posY;
}

/*!
 * @brief This function returns a reference to member posY
 * @return Reference to member posY
 */
float& SimOneDDS_Data_Obstacle_Entry::posY()
{
    return m_posY;
}

/*!
 * @brief This function sets a value in member posZ
 * @param _posZ New value for member posZ
 */
void SimOneDDS_Data_Obstacle_Entry::posZ(
        float _posZ)
{
    m_posZ = _posZ;
}

/*!
 * @brief This function returns the value of member posZ
 * @return Value of member posZ
 */
float SimOneDDS_Data_Obstacle_Entry::posZ() const
{
    return m_posZ;
}

/*!
 * @brief This function returns a reference to member posZ
 * @return Reference to member posZ
 */
float& SimOneDDS_Data_Obstacle_Entry::posZ()
{
    return m_posZ;
}

/*!
 * @brief This function sets a value in member oriX
 * @param _oriX New value for member oriX
 */
void SimOneDDS_Data_Obstacle_Entry::oriX(
        float _oriX)
{
    m_oriX = _oriX;
}

/*!
 * @brief This function returns the value of member oriX
 * @return Value of member oriX
 */
float SimOneDDS_Data_Obstacle_Entry::oriX() const
{
    return m_oriX;
}

/*!
 * @brief This function returns a reference to member oriX
 * @return Reference to member oriX
 */
float& SimOneDDS_Data_Obstacle_Entry::oriX()
{
    return m_oriX;
}

/*!
 * @brief This function sets a value in member oriY
 * @param _oriY New value for member oriY
 */
void SimOneDDS_Data_Obstacle_Entry::oriY(
        float _oriY)
{
    m_oriY = _oriY;
}

/*!
 * @brief This function returns the value of member oriY
 * @return Value of member oriY
 */
float SimOneDDS_Data_Obstacle_Entry::oriY() const
{
    return m_oriY;
}

/*!
 * @brief This function returns a reference to member oriY
 * @return Reference to member oriY
 */
float& SimOneDDS_Data_Obstacle_Entry::oriY()
{
    return m_oriY;
}

/*!
 * @brief This function sets a value in member oriZ
 * @param _oriZ New value for member oriZ
 */
void SimOneDDS_Data_Obstacle_Entry::oriZ(
        float _oriZ)
{
    m_oriZ = _oriZ;
}

/*!
 * @brief This function returns the value of member oriZ
 * @return Value of member oriZ
 */
float SimOneDDS_Data_Obstacle_Entry::oriZ() const
{
    return m_oriZ;
}

/*!
 * @brief This function returns a reference to member oriZ
 * @return Reference to member oriZ
 */
float& SimOneDDS_Data_Obstacle_Entry::oriZ()
{
    return m_oriZ;
}

/*!
 * @brief This function sets a value in member velX
 * @param _velX New value for member velX
 */
void SimOneDDS_Data_Obstacle_Entry::velX(
        float _velX)
{
    m_velX = _velX;
}

/*!
 * @brief This function returns the value of member velX
 * @return Value of member velX
 */
float SimOneDDS_Data_Obstacle_Entry::velX() const
{
    return m_velX;
}

/*!
 * @brief This function returns a reference to member velX
 * @return Reference to member velX
 */
float& SimOneDDS_Data_Obstacle_Entry::velX()
{
    return m_velX;
}

/*!
 * @brief This function sets a value in member velY
 * @param _velY New value for member velY
 */
void SimOneDDS_Data_Obstacle_Entry::velY(
        float _velY)
{
    m_velY = _velY;
}

/*!
 * @brief This function returns the value of member velY
 * @return Value of member velY
 */
float SimOneDDS_Data_Obstacle_Entry::velY() const
{
    return m_velY;
}

/*!
 * @brief This function returns a reference to member velY
 * @return Reference to member velY
 */
float& SimOneDDS_Data_Obstacle_Entry::velY()
{
    return m_velY;
}

/*!
 * @brief This function sets a value in member velZ
 * @param _velZ New value for member velZ
 */
void SimOneDDS_Data_Obstacle_Entry::velZ(
        float _velZ)
{
    m_velZ = _velZ;
}

/*!
 * @brief This function returns the value of member velZ
 * @return Value of member velZ
 */
float SimOneDDS_Data_Obstacle_Entry::velZ() const
{
    return m_velZ;
}

/*!
 * @brief This function returns a reference to member velZ
 * @return Reference to member velZ
 */
float& SimOneDDS_Data_Obstacle_Entry::velZ()
{
    return m_velZ;
}

/*!
 * @brief This function sets a value in member length
 * @param _length New value for member length
 */
void SimOneDDS_Data_Obstacle_Entry::length(
        float _length)
{
    m_length = _length;
}

/*!
 * @brief This function returns the value of member length
 * @return Value of member length
 */
float SimOneDDS_Data_Obstacle_Entry::length() const
{
    return m_length;
}

/*!
 * @brief This function returns a reference to member length
 * @return Reference to member length
 */
float& SimOneDDS_Data_Obstacle_Entry::length()
{
    return m_length;
}

/*!
 * @brief This function sets a value in member width
 * @param _width New value for member width
 */
void SimOneDDS_Data_Obstacle_Entry::width(
        float _width)
{
    m_width = _width;
}

/*!
 * @brief This function returns the value of member width
 * @return Value of member width
 */
float SimOneDDS_Data_Obstacle_Entry::width() const
{
    return m_width;
}

/*!
 * @brief This function returns a reference to member width
 * @return Reference to member width
 */
float& SimOneDDS_Data_Obstacle_Entry::width()
{
    return m_width;
}

/*!
 * @brief This function sets a value in member height
 * @param _height New value for member height
 */
void SimOneDDS_Data_Obstacle_Entry::height(
        float _height)
{
    m_height = _height;
}

/*!
 * @brief This function returns the value of member height
 * @return Value of member height
 */
float SimOneDDS_Data_Obstacle_Entry::height() const
{
    return m_height;
}

/*!
 * @brief This function returns a reference to member height
 * @return Reference to member height
 */
float& SimOneDDS_Data_Obstacle_Entry::height()
{
    return m_height;
}

/*!
 * @brief This function sets a value in member accelX
 * @param _accelX New value for member accelX
 */
void SimOneDDS_Data_Obstacle_Entry::accelX(
        float _accelX)
{
    m_accelX = _accelX;
}

/*!
 * @brief This function returns the value of member accelX
 * @return Value of member accelX
 */
float SimOneDDS_Data_Obstacle_Entry::accelX() const
{
    return m_accelX;
}

/*!
 * @brief This function returns a reference to member accelX
 * @return Reference to member accelX
 */
float& SimOneDDS_Data_Obstacle_Entry::accelX()
{
    return m_accelX;
}

/*!
 * @brief This function sets a value in member accelY
 * @param _accelY New value for member accelY
 */
void SimOneDDS_Data_Obstacle_Entry::accelY(
        float _accelY)
{
    m_accelY = _accelY;
}

/*!
 * @brief This function returns the value of member accelY
 * @return Value of member accelY
 */
float SimOneDDS_Data_Obstacle_Entry::accelY() const
{
    return m_accelY;
}

/*!
 * @brief This function returns a reference to member accelY
 * @return Reference to member accelY
 */
float& SimOneDDS_Data_Obstacle_Entry::accelY()
{
    return m_accelY;
}

/*!
 * @brief This function sets a value in member accelZ
 * @param _accelZ New value for member accelZ
 */
void SimOneDDS_Data_Obstacle_Entry::accelZ(
        float _accelZ)
{
    m_accelZ = _accelZ;
}

/*!
 * @brief This function returns the value of member accelZ
 * @return Value of member accelZ
 */
float SimOneDDS_Data_Obstacle_Entry::accelZ() const
{
    return m_accelZ;
}

/*!
 * @brief This function returns a reference to member accelZ
 * @return Reference to member accelZ
 */
float& SimOneDDS_Data_Obstacle_Entry::accelZ()
{
    return m_accelZ;
}


size_t SimOneDDS_Data_Obstacle_Entry::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t current_align = current_alignment;






















    return current_align;
}

bool SimOneDDS_Data_Obstacle_Entry::isKeyDefined()
{
    return false;
}

void SimOneDDS_Data_Obstacle_Entry::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
                       
}

SimOneDDS_Data_Obstacle::SimOneDDS_Data_Obstacle()
{
    // m_obstacleSize com.eprosima.idl.parser.typecode.PrimitiveTypeCode@3d3fcdb0
    m_obstacleSize = 0;
    // m_obstacle com.eprosima.idl.parser.typecode.ArrayTypeCode@641147d0


}

SimOneDDS_Data_Obstacle::~SimOneDDS_Data_Obstacle()
{


}

SimOneDDS_Data_Obstacle::SimOneDDS_Data_Obstacle(
        const SimOneDDS_Data_Obstacle& x)
{
    m_obstacleSize = x.m_obstacleSize;
    m_obstacle = x.m_obstacle;
}

SimOneDDS_Data_Obstacle::SimOneDDS_Data_Obstacle(
        SimOneDDS_Data_Obstacle&& x)
{
    m_obstacleSize = x.m_obstacleSize;
    m_obstacle = std::move(x.m_obstacle);
}

SimOneDDS_Data_Obstacle& SimOneDDS_Data_Obstacle::operator =(
        const SimOneDDS_Data_Obstacle& x)
{

    m_obstacleSize = x.m_obstacleSize;
    m_obstacle = x.m_obstacle;

    return *this;
}

SimOneDDS_Data_Obstacle& SimOneDDS_Data_Obstacle::operator =(
        SimOneDDS_Data_Obstacle&& x)
{

    m_obstacleSize = x.m_obstacleSize;
    m_obstacle = std::move(x.m_obstacle);

    return *this;
}

bool SimOneDDS_Data_Obstacle::operator ==(
        const SimOneDDS_Data_Obstacle& x) const
{

    return (m_obstacleSize == x.m_obstacleSize && m_obstacle == x.m_obstacle);
}

bool SimOneDDS_Data_Obstacle::operator !=(
        const SimOneDDS_Data_Obstacle& x) const
{
    return !(*this == x);
}

size_t SimOneDDS_Data_Obstacle::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);



    for(size_t a = 0; a < (255); ++a)
    {
        current_alignment += SimOneDDS_Data_Obstacle_Entry::getMaxCdrSerializedSize(current_alignment);}

    return current_alignment - initial_alignment;
}

size_t SimOneDDS_Data_Obstacle::getCdrSerializedSize(
        const SimOneDDS_Data_Obstacle& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);



    for(size_t a = 0; a < data.obstacle().size(); ++a)
    {
            current_alignment += SimOneDDS_Data_Obstacle_Entry::getCdrSerializedSize(data.obstacle().at(a), current_alignment);
    }

    return current_alignment - initial_alignment;
}

void SimOneDDS_Data_Obstacle::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_obstacleSize;
    scdr << m_obstacle;


}

void SimOneDDS_Data_Obstacle::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_obstacleSize;
    dcdr >> m_obstacle;

}

/*!
 * @brief This function sets a value in member obstacleSize
 * @param _obstacleSize New value for member obstacleSize
 */
void SimOneDDS_Data_Obstacle::obstacleSize(
        int32_t _obstacleSize)
{
    m_obstacleSize = _obstacleSize;
}

/*!
 * @brief This function returns the value of member obstacleSize
 * @return Value of member obstacleSize
 */
int32_t SimOneDDS_Data_Obstacle::obstacleSize() const
{
    return m_obstacleSize;
}

/*!
 * @brief This function returns a reference to member obstacleSize
 * @return Reference to member obstacleSize
 */
int32_t& SimOneDDS_Data_Obstacle::obstacleSize()
{
    return m_obstacleSize;
}

/*!
 * @brief This function copies the value in member obstacle
 * @param _obstacle New value to be copied in member obstacle
 */
void SimOneDDS_Data_Obstacle::obstacle(
        const std::array<SimOneDDS_Data_Obstacle_Entry, 255>& _obstacle)
{
    m_obstacle = _obstacle;
}

/*!
 * @brief This function moves the value in member obstacle
 * @param _obstacle New value to be moved in member obstacle
 */
void SimOneDDS_Data_Obstacle::obstacle(
        std::array<SimOneDDS_Data_Obstacle_Entry, 255>&& _obstacle)
{
    m_obstacle = std::move(_obstacle);
}

/*!
 * @brief This function returns a constant reference to member obstacle
 * @return Constant reference to member obstacle
 */
const std::array<SimOneDDS_Data_Obstacle_Entry, 255>& SimOneDDS_Data_Obstacle::obstacle() const
{
    return m_obstacle;
}

/*!
 * @brief This function returns a reference to member obstacle
 * @return Reference to member obstacle
 */
std::array<SimOneDDS_Data_Obstacle_Entry, 255>& SimOneDDS_Data_Obstacle::obstacle()
{
    return m_obstacle;
}

size_t SimOneDDS_Data_Obstacle::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t current_align = current_alignment;





    return current_align;
}

bool SimOneDDS_Data_Obstacle::isKeyDefined()
{
    return false;
}

void SimOneDDS_Data_Obstacle::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
      
}
