// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file SimOne_Data.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "SimOne_Data.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

SimOneDDS_Data::SimOneDDS_Data()
{
    // m_timestamp com.eprosima.idl.parser.typecode.PrimitiveTypeCode@1d371b2d
    m_timestamp = 0;
    // m_frame com.eprosima.idl.parser.typecode.PrimitiveTypeCode@543c6f6d
    m_frame = 0;
    // m_version com.eprosima.idl.parser.typecode.PrimitiveTypeCode@13eb8acf
    m_version = 0;

}

SimOneDDS_Data::~SimOneDDS_Data()
{



}

SimOneDDS_Data::SimOneDDS_Data(
        const SimOneDDS_Data& x)
{
    m_timestamp = x.m_timestamp;
    m_frame = x.m_frame;
    m_version = x.m_version;
}

SimOneDDS_Data::SimOneDDS_Data(
        SimOneDDS_Data&& x)
{
    m_timestamp = x.m_timestamp;
    m_frame = x.m_frame;
    m_version = x.m_version;
}

SimOneDDS_Data& SimOneDDS_Data::operator =(
        const SimOneDDS_Data& x)
{

    m_timestamp = x.m_timestamp;
    m_frame = x.m_frame;
    m_version = x.m_version;

    return *this;
}

SimOneDDS_Data& SimOneDDS_Data::operator =(
        SimOneDDS_Data&& x)
{

    m_timestamp = x.m_timestamp;
    m_frame = x.m_frame;
    m_version = x.m_version;

    return *this;
}

bool SimOneDDS_Data::operator ==(
        const SimOneDDS_Data& x) const
{

    return (m_timestamp == x.m_timestamp && m_frame == x.m_frame && m_version == x.m_version);
}

bool SimOneDDS_Data::operator !=(
        const SimOneDDS_Data& x) const
{
    return !(*this == x);
}

size_t SimOneDDS_Data::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t initial_alignment = current_alignment;


    current_alignment += 8 + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);



    return current_alignment - initial_alignment;
}

size_t SimOneDDS_Data::getCdrSerializedSize(
        const SimOneDDS_Data& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += 8 + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);



    return current_alignment - initial_alignment;
}

void SimOneDDS_Data::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_timestamp;
    scdr << m_frame;
    scdr << m_version;

}

void SimOneDDS_Data::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_timestamp;
    dcdr >> m_frame;
    dcdr >> m_version;
}

/*!
 * @brief This function sets a value in member timestamp
 * @param _timestamp New value for member timestamp
 */
void SimOneDDS_Data::timestamp(
        int64_t _timestamp)
{
    m_timestamp = _timestamp;
}

/*!
 * @brief This function returns the value of member timestamp
 * @return Value of member timestamp
 */
int64_t SimOneDDS_Data::timestamp() const
{
    return m_timestamp;
}

/*!
 * @brief This function returns a reference to member timestamp
 * @return Reference to member timestamp
 */
int64_t& SimOneDDS_Data::timestamp()
{
    return m_timestamp;
}

/*!
 * @brief This function sets a value in member frame
 * @param _frame New value for member frame
 */
void SimOneDDS_Data::frame(
        int32_t _frame)
{
    m_frame = _frame;
}

/*!
 * @brief This function returns the value of member frame
 * @return Value of member frame
 */
int32_t SimOneDDS_Data::frame() const
{
    return m_frame;
}

/*!
 * @brief This function returns a reference to member frame
 * @return Reference to member frame
 */
int32_t& SimOneDDS_Data::frame()
{
    return m_frame;
}

/*!
 * @brief This function sets a value in member version
 * @param _version New value for member version
 */
void SimOneDDS_Data::version(
        int32_t _version)
{
    m_version = _version;
}

/*!
 * @brief This function returns the value of member version
 * @return Value of member version
 */
int32_t SimOneDDS_Data::version() const
{
    return m_version;
}

/*!
 * @brief This function returns a reference to member version
 * @return Reference to member version
 */
int32_t& SimOneDDS_Data::version()
{
    return m_version;
}


size_t SimOneDDS_Data::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t current_align = current_alignment;






    return current_align;
}

bool SimOneDDS_Data::isKeyDefined()
{
    return false;
}

void SimOneDDS_Data::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
       
}
