// Generated by gencpp from file msg_gen/radardetection.msg
// DO NOT EDIT!


#ifndef MSG_GEN_MESSAGE_RADARDETECTION_H
#define MSG_GEN_MESSAGE_RADARDETECTION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <msg_gen/SimOne_Data_RadarDetection_Entry.h>

namespace msg_gen
{
template <class ContainerAllocator>
struct radardetection_
{
  typedef radardetection_<ContainerAllocator> Type;

  radardetection_()
    : detectNum(0)
    , detections()  {
    }
  radardetection_(const ContainerAllocator& _alloc)
    : detectNum(0)
    , detections(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _detectNum_type;
  _detectNum_type detectNum;

   typedef std::vector< ::msg_gen::SimOne_Data_RadarDetection_Entry_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::msg_gen::SimOne_Data_RadarDetection_Entry_<ContainerAllocator> >::other >  _detections_type;
  _detections_type detections;





  typedef boost::shared_ptr< ::msg_gen::radardetection_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::msg_gen::radardetection_<ContainerAllocator> const> ConstPtr;

}; // struct radardetection_

typedef ::msg_gen::radardetection_<std::allocator<void> > radardetection;

typedef boost::shared_ptr< ::msg_gen::radardetection > radardetectionPtr;
typedef boost::shared_ptr< ::msg_gen::radardetection const> radardetectionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::msg_gen::radardetection_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::msg_gen::radardetection_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::msg_gen::radardetection_<ContainerAllocator1> & lhs, const ::msg_gen::radardetection_<ContainerAllocator2> & rhs)
{
  return lhs.detectNum == rhs.detectNum &&
    lhs.detections == rhs.detections;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::msg_gen::radardetection_<ContainerAllocator1> & lhs, const ::msg_gen::radardetection_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace msg_gen

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::msg_gen::radardetection_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msg_gen::radardetection_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_gen::radardetection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_gen::radardetection_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_gen::radardetection_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_gen::radardetection_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::msg_gen::radardetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "34b8ef4c73bcbbcb9d8a568523cafd9d";
  }

  static const char* value(const ::msg_gen::radardetection_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x34b8ef4c73bcbbcbULL;
  static const uint64_t static_value2 = 0x9d8a568523cafd9dULL;
};

template<class ContainerAllocator>
struct DataType< ::msg_gen::radardetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "msg_gen/radardetection";
  }

  static const char* value(const ::msg_gen::radardetection_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::msg_gen::radardetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 detectNum\n"
"SimOne_Data_RadarDetection_Entry[] detections\n"
"================================================================================\n"
"MSG: msg_gen/SimOne_Data_RadarDetection_Entry\n"
"int32 id\n"
"int32 subId\n"
"SimOne_Obstacle_Type type\n"
"float64 posX\n"
"float64 posY\n"
"float64 posZ\n"
"float64 velX\n"
"float64 velY\n"
"float64 velZ\n"
"float64 range\n"
"float64 rangeRate\n"
"float64 azimuth\n"
"float64 vertical\n"
"float64 snrdb\n"
"float64 rcsdb\n"
"float64 probability\n"
"================================================================================\n"
"MSG: msg_gen/SimOne_Obstacle_Type\n"
"uint8 ESimOne_Obstacle_Type_Unknown = 0\n"
"uint8 ESimOne_Obstacle_Type_Pedestrian = 4\n"
"uint8 ESimOne_Obstacle_Type_Pole = 5\n"
"uint8 ESimOne_Obstacle_Type_Car = 6\n"
"uint8 ESimOne_Obstacle_Type_Static = 7\n"
"uint8 ESimOne_Obstacle_Type_Bicycle = 8\n"
"uint8 ESimOne_Obstacle_Type_Fence = 9\n"
"uint8 ESimOne_Obstacle_Type_RoadMark = 12\n"
"uint8 ESimOne_Obstacle_Type_TrafficSign = 13\n"
"uint8 ESimOne_Obstacle_Type_TrafficLight = 15\n"
"uint8 ESimOne_Obstacle_Type_Rider = 17\n"
"uint8 ESimOne_Obstacle_Type_Truck = 18\n"
"uint8 ESimOne_Obstacle_Type_Bus = 19\n"
"uint8 ESimOne_Obstacle_Type_SpecialVehicle = 20\n"
"uint8 ESimOne_Obstacle_Type_Motorcycle = 21\n"
"uint8 ESimOne_Obstacle_Type_Dynamic = 22\n"
"uint8 ESimOne_Obstacle_Type_GuardRail = 23\n"
"uint8 ESimOne_Obstacle_Type_SpeedLimitSign = 26\n"
"uint8 ESimOne_Obstacle_Type_BicycleStatic = 27\n"
"uint8 ESimOne_Obstacle_Type_RoadObstacle = 29\n"
"uint32 SimOne_Obstacle_Type\n"
;
  }

  static const char* value(const ::msg_gen::radardetection_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::msg_gen::radardetection_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.detectNum);
      stream.next(m.detections);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct radardetection_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::msg_gen::radardetection_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::msg_gen::radardetection_<ContainerAllocator>& v)
  {
    s << indent << "detectNum: ";
    Printer<int32_t>::stream(s, indent + "  ", v.detectNum);
    s << indent << "detections[]" << std::endl;
    for (size_t i = 0; i < v.detections.size(); ++i)
    {
      s << indent << "  detections[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::msg_gen::SimOne_Data_RadarDetection_Entry_<ContainerAllocator> >::stream(s, indent + "    ", v.detections[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSG_GEN_MESSAGE_RADARDETECTION_H
