// Generated by gencpp from file msg_gen/signal_lights.msg
// DO NOT EDIT!


#ifndef MSG_GEN_MESSAGE_SIGNAL_LIGHTS_H
#define MSG_GEN_MESSAGE_SIGNAL_LIGHTS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace msg_gen
{
template <class ContainerAllocator>
struct signal_lights_
{
  typedef signal_lights_<ContainerAllocator> Type;

  signal_lights_()
    : signalLights(0)  {
    }
  signal_lights_(const ContainerAllocator& _alloc)
    : signalLights(0)  {
  (void)_alloc;
    }



   typedef uint32_t _signalLights_type;
  _signalLights_type signalLights;





  typedef boost::shared_ptr< ::msg_gen::signal_lights_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::msg_gen::signal_lights_<ContainerAllocator> const> ConstPtr;

}; // struct signal_lights_

typedef ::msg_gen::signal_lights_<std::allocator<void> > signal_lights;

typedef boost::shared_ptr< ::msg_gen::signal_lights > signal_lightsPtr;
typedef boost::shared_ptr< ::msg_gen::signal_lights const> signal_lightsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::msg_gen::signal_lights_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::msg_gen::signal_lights_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::msg_gen::signal_lights_<ContainerAllocator1> & lhs, const ::msg_gen::signal_lights_<ContainerAllocator2> & rhs)
{
  return lhs.signalLights == rhs.signalLights;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::msg_gen::signal_lights_<ContainerAllocator1> & lhs, const ::msg_gen::signal_lights_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace msg_gen

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::msg_gen::signal_lights_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msg_gen::signal_lights_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_gen::signal_lights_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_gen::signal_lights_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_gen::signal_lights_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_gen::signal_lights_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::msg_gen::signal_lights_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2075fdc7df545f66c0117fc96053810e";
  }

  static const char* value(const ::msg_gen::signal_lights_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2075fdc7df545f66ULL;
  static const uint64_t static_value2 = 0xc0117fc96053810eULL;
};

template<class ContainerAllocator>
struct DataType< ::msg_gen::signal_lights_<ContainerAllocator> >
{
  static const char* value()
  {
    return "msg_gen/signal_lights";
  }

  static const char* value(const ::msg_gen::signal_lights_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::msg_gen::signal_lights_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 signalLights\n"
;
  }

  static const char* value(const ::msg_gen::signal_lights_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::msg_gen::signal_lights_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.signalLights);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct signal_lights_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::msg_gen::signal_lights_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::msg_gen::signal_lights_<ContainerAllocator>& v)
  {
    s << indent << "signalLights: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.signalLights);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSG_GEN_MESSAGE_SIGNAL_LIGHTS_H
