// Generated by gencpp from file msg_gen/SimOne_Data_UltrasonicRadarDetection_Entry.msg
// DO NOT EDIT!


#ifndef MSG_GEN_MESSAGE_SIMONE_DATA_ULTRASONICRADARDETECTION_ENTRY_H
#define MSG_GEN_MESSAGE_SIMONE_DATA_ULTRASONICRADARDETECTION_ENTRY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace msg_gen
{
template <class ContainerAllocator>
struct SimOne_Data_UltrasonicRadarDetection_Entry_
{
  typedef SimOne_Data_UltrasonicRadarDetection_Entry_<ContainerAllocator> Type;

  SimOne_Data_UltrasonicRadarDetection_Entry_()
    : obstacleRanges(0.0)
    , x(0.0)
    , y(0.0)  {
    }
  SimOne_Data_UltrasonicRadarDetection_Entry_(const ContainerAllocator& _alloc)
    : obstacleRanges(0.0)
    , x(0.0)
    , y(0.0)  {
  (void)_alloc;
    }



   typedef double _obstacleRanges_type;
  _obstacleRanges_type obstacleRanges;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;





  typedef boost::shared_ptr< ::msg_gen::SimOne_Data_UltrasonicRadarDetection_Entry_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::msg_gen::SimOne_Data_UltrasonicRadarDetection_Entry_<ContainerAllocator> const> ConstPtr;

}; // struct SimOne_Data_UltrasonicRadarDetection_Entry_

typedef ::msg_gen::SimOne_Data_UltrasonicRadarDetection_Entry_<std::allocator<void> > SimOne_Data_UltrasonicRadarDetection_Entry;

typedef boost::shared_ptr< ::msg_gen::SimOne_Data_UltrasonicRadarDetection_Entry > SimOne_Data_UltrasonicRadarDetection_EntryPtr;
typedef boost::shared_ptr< ::msg_gen::SimOne_Data_UltrasonicRadarDetection_Entry const> SimOne_Data_UltrasonicRadarDetection_EntryConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::msg_gen::SimOne_Data_UltrasonicRadarDetection_Entry_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::msg_gen::SimOne_Data_UltrasonicRadarDetection_Entry_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::msg_gen::SimOne_Data_UltrasonicRadarDetection_Entry_<ContainerAllocator1> & lhs, const ::msg_gen::SimOne_Data_UltrasonicRadarDetection_Entry_<ContainerAllocator2> & rhs)
{
  return lhs.obstacleRanges == rhs.obstacleRanges &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::msg_gen::SimOne_Data_UltrasonicRadarDetection_Entry_<ContainerAllocator1> & lhs, const ::msg_gen::SimOne_Data_UltrasonicRadarDetection_Entry_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace msg_gen

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::msg_gen::SimOne_Data_UltrasonicRadarDetection_Entry_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msg_gen::SimOne_Data_UltrasonicRadarDetection_Entry_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_gen::SimOne_Data_UltrasonicRadarDetection_Entry_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_gen::SimOne_Data_UltrasonicRadarDetection_Entry_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_gen::SimOne_Data_UltrasonicRadarDetection_Entry_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_gen::SimOne_Data_UltrasonicRadarDetection_Entry_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::msg_gen::SimOne_Data_UltrasonicRadarDetection_Entry_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d8e1a6c334246a8896683012513ec3ca";
  }

  static const char* value(const ::msg_gen::SimOne_Data_UltrasonicRadarDetection_Entry_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd8e1a6c334246a88ULL;
  static const uint64_t static_value2 = 0x96683012513ec3caULL;
};

template<class ContainerAllocator>
struct DataType< ::msg_gen::SimOne_Data_UltrasonicRadarDetection_Entry_<ContainerAllocator> >
{
  static const char* value()
  {
    return "msg_gen/SimOne_Data_UltrasonicRadarDetection_Entry";
  }

  static const char* value(const ::msg_gen::SimOne_Data_UltrasonicRadarDetection_Entry_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::msg_gen::SimOne_Data_UltrasonicRadarDetection_Entry_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 obstacleRanges\n"
"float64 x\n"
"float64 y\n"
;
  }

  static const char* value(const ::msg_gen::SimOne_Data_UltrasonicRadarDetection_Entry_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::msg_gen::SimOne_Data_UltrasonicRadarDetection_Entry_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.obstacleRanges);
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SimOne_Data_UltrasonicRadarDetection_Entry_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::msg_gen::SimOne_Data_UltrasonicRadarDetection_Entry_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::msg_gen::SimOne_Data_UltrasonicRadarDetection_Entry_<ContainerAllocator>& v)
  {
    s << indent << "obstacleRanges: ";
    Printer<double>::stream(s, indent + "  ", v.obstacleRanges);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSG_GEN_MESSAGE_SIMONE_DATA_ULTRASONICRADARDETECTION_ENTRY_H
