// Generated by gencpp from file msg_gen/waypoints_entry.msg
// DO NOT EDIT!


#ifndef MSG_GEN_MESSAGE_WAYPOINTS_ENTRY_H
#define MSG_GEN_MESSAGE_WAYPOINTS_ENTRY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace msg_gen
{
template <class ContainerAllocator>
struct waypoints_entry_
{
  typedef waypoints_entry_<ContainerAllocator> Type;

  waypoints_entry_()
    : index(0)
    , posX(0.0)
    , posY(0.0)
    , heading_x(0.0)
    , heading_y(0.0)
    , heading_z(0.0)
    , heading_w(0.0)  {
    }
  waypoints_entry_(const ContainerAllocator& _alloc)
    : index(0)
    , posX(0.0)
    , posY(0.0)
    , heading_x(0.0)
    , heading_y(0.0)
    , heading_z(0.0)
    , heading_w(0.0)  {
  (void)_alloc;
    }



   typedef uint32_t _index_type;
  _index_type index;

   typedef double _posX_type;
  _posX_type posX;

   typedef double _posY_type;
  _posY_type posY;

   typedef double _heading_x_type;
  _heading_x_type heading_x;

   typedef double _heading_y_type;
  _heading_y_type heading_y;

   typedef double _heading_z_type;
  _heading_z_type heading_z;

   typedef double _heading_w_type;
  _heading_w_type heading_w;





  typedef boost::shared_ptr< ::msg_gen::waypoints_entry_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::msg_gen::waypoints_entry_<ContainerAllocator> const> ConstPtr;

}; // struct waypoints_entry_

typedef ::msg_gen::waypoints_entry_<std::allocator<void> > waypoints_entry;

typedef boost::shared_ptr< ::msg_gen::waypoints_entry > waypoints_entryPtr;
typedef boost::shared_ptr< ::msg_gen::waypoints_entry const> waypoints_entryConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::msg_gen::waypoints_entry_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::msg_gen::waypoints_entry_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::msg_gen::waypoints_entry_<ContainerAllocator1> & lhs, const ::msg_gen::waypoints_entry_<ContainerAllocator2> & rhs)
{
  return lhs.index == rhs.index &&
    lhs.posX == rhs.posX &&
    lhs.posY == rhs.posY &&
    lhs.heading_x == rhs.heading_x &&
    lhs.heading_y == rhs.heading_y &&
    lhs.heading_z == rhs.heading_z &&
    lhs.heading_w == rhs.heading_w;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::msg_gen::waypoints_entry_<ContainerAllocator1> & lhs, const ::msg_gen::waypoints_entry_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace msg_gen

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::msg_gen::waypoints_entry_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msg_gen::waypoints_entry_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_gen::waypoints_entry_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_gen::waypoints_entry_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_gen::waypoints_entry_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_gen::waypoints_entry_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::msg_gen::waypoints_entry_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1ff1e76d9734fbfec4fca661da6b0408";
  }

  static const char* value(const ::msg_gen::waypoints_entry_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1ff1e76d9734fbfeULL;
  static const uint64_t static_value2 = 0xc4fca661da6b0408ULL;
};

template<class ContainerAllocator>
struct DataType< ::msg_gen::waypoints_entry_<ContainerAllocator> >
{
  static const char* value()
  {
    return "msg_gen/waypoints_entry";
  }

  static const char* value(const ::msg_gen::waypoints_entry_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::msg_gen::waypoints_entry_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 index\n"
"float64 posX\n"
"float64 posY\n"
"\n"
"float64 heading_x\n"
"float64 heading_y\n"
"float64 heading_z\n"
"float64 heading_w\n"
;
  }

  static const char* value(const ::msg_gen::waypoints_entry_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::msg_gen::waypoints_entry_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.index);
      stream.next(m.posX);
      stream.next(m.posY);
      stream.next(m.heading_x);
      stream.next(m.heading_y);
      stream.next(m.heading_z);
      stream.next(m.heading_w);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct waypoints_entry_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::msg_gen::waypoints_entry_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::msg_gen::waypoints_entry_<ContainerAllocator>& v)
  {
    s << indent << "index: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.index);
    s << indent << "posX: ";
    Printer<double>::stream(s, indent + "  ", v.posX);
    s << indent << "posY: ";
    Printer<double>::stream(s, indent + "  ", v.posY);
    s << indent << "heading_x: ";
    Printer<double>::stream(s, indent + "  ", v.heading_x);
    s << indent << "heading_y: ";
    Printer<double>::stream(s, indent + "  ", v.heading_y);
    s << indent << "heading_z: ";
    Printer<double>::stream(s, indent + "  ", v.heading_z);
    s << indent << "heading_w: ";
    Printer<double>::stream(s, indent + "  ", v.heading_w);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSG_GEN_MESSAGE_WAYPOINTS_ENTRY_H
