// Generated by gencpp from file msg_gen/pose_control.msg
// DO NOT EDIT!


#ifndef MSG_GEN_MESSAGE_POSE_CONTROL_H
#define MSG_GEN_MESSAGE_POSE_CONTROL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace msg_gen
{
template <class ContainerAllocator>
struct pose_control_
{
  typedef pose_control_<ContainerAllocator> Type;

  pose_control_()
    : posX(0.0)
    , posY(0.0)
    , posZ(0.0)
    , oriX(0.0)
    , oriY(0.0)
    , oriZ(0.0)
    , autoZ(false)  {
    }
  pose_control_(const ContainerAllocator& _alloc)
    : posX(0.0)
    , posY(0.0)
    , posZ(0.0)
    , oriX(0.0)
    , oriY(0.0)
    , oriZ(0.0)
    , autoZ(false)  {
  (void)_alloc;
    }



   typedef double _posX_type;
  _posX_type posX;

   typedef double _posY_type;
  _posY_type posY;

   typedef double _posZ_type;
  _posZ_type posZ;

   typedef double _oriX_type;
  _oriX_type oriX;

   typedef double _oriY_type;
  _oriY_type oriY;

   typedef double _oriZ_type;
  _oriZ_type oriZ;

   typedef uint8_t _autoZ_type;
  _autoZ_type autoZ;





  typedef boost::shared_ptr< ::msg_gen::pose_control_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::msg_gen::pose_control_<ContainerAllocator> const> ConstPtr;

}; // struct pose_control_

typedef ::msg_gen::pose_control_<std::allocator<void> > pose_control;

typedef boost::shared_ptr< ::msg_gen::pose_control > pose_controlPtr;
typedef boost::shared_ptr< ::msg_gen::pose_control const> pose_controlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::msg_gen::pose_control_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::msg_gen::pose_control_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::msg_gen::pose_control_<ContainerAllocator1> & lhs, const ::msg_gen::pose_control_<ContainerAllocator2> & rhs)
{
  return lhs.posX == rhs.posX &&
    lhs.posY == rhs.posY &&
    lhs.posZ == rhs.posZ &&
    lhs.oriX == rhs.oriX &&
    lhs.oriY == rhs.oriY &&
    lhs.oriZ == rhs.oriZ &&
    lhs.autoZ == rhs.autoZ;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::msg_gen::pose_control_<ContainerAllocator1> & lhs, const ::msg_gen::pose_control_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace msg_gen

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::msg_gen::pose_control_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msg_gen::pose_control_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_gen::pose_control_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_gen::pose_control_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_gen::pose_control_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_gen::pose_control_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::msg_gen::pose_control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "574852063b8e75bb6443efaf521ec364";
  }

  static const char* value(const ::msg_gen::pose_control_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x574852063b8e75bbULL;
  static const uint64_t static_value2 = 0x6443efaf521ec364ULL;
};

template<class ContainerAllocator>
struct DataType< ::msg_gen::pose_control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "msg_gen/pose_control";
  }

  static const char* value(const ::msg_gen::pose_control_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::msg_gen::pose_control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 posX\n"
"float64 posY\n"
"float64 posZ\n"
"float64 oriX\n"
"float64 oriY\n"
"float64 oriZ\n"
"bool autoZ\n"
;
  }

  static const char* value(const ::msg_gen::pose_control_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::msg_gen::pose_control_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.posX);
      stream.next(m.posY);
      stream.next(m.posZ);
      stream.next(m.oriX);
      stream.next(m.oriY);
      stream.next(m.oriZ);
      stream.next(m.autoZ);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pose_control_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::msg_gen::pose_control_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::msg_gen::pose_control_<ContainerAllocator>& v)
  {
    s << indent << "posX: ";
    Printer<double>::stream(s, indent + "  ", v.posX);
    s << indent << "posY: ";
    Printer<double>::stream(s, indent + "  ", v.posY);
    s << indent << "posZ: ";
    Printer<double>::stream(s, indent + "  ", v.posZ);
    s << indent << "oriX: ";
    Printer<double>::stream(s, indent + "  ", v.oriX);
    s << indent << "oriY: ";
    Printer<double>::stream(s, indent + "  ", v.oriY);
    s << indent << "oriZ: ";
    Printer<double>::stream(s, indent + "  ", v.oriZ);
    s << indent << "autoZ: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.autoZ);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSG_GEN_MESSAGE_POSE_CONTROL_H
