// Generated by gencpp from file msg_gen/SimOne_Driver_Status.msg
// DO NOT EDIT!


#ifndef MSG_GEN_MESSAGE_SIMONE_DRIVER_STATUS_H
#define MSG_GEN_MESSAGE_SIMONE_DRIVER_STATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace msg_gen
{
template <class ContainerAllocator>
struct SimOne_Driver_Status_
{
  typedef SimOne_Driver_Status_<ContainerAllocator> Type;

  SimOne_Driver_Status_()
    : SimOne_Driver_Status(0)  {
    }
  SimOne_Driver_Status_(const ContainerAllocator& _alloc)
    : SimOne_Driver_Status(0)  {
  (void)_alloc;
    }



   typedef uint32_t _SimOne_Driver_Status_type;
  _SimOne_Driver_Status_type SimOne_Driver_Status;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(ESimOne_Driver_Status_Unknown)
  #undef ESimOne_Driver_Status_Unknown
#endif
#if defined(_WIN32) && defined(ESimOne_Driver_Status_Controlling)
  #undef ESimOne_Driver_Status_Controlling
#endif
#if defined(_WIN32) && defined(ESimOne_Driver_Status_Disabled)
  #undef ESimOne_Driver_Status_Disabled
#endif

  enum {
    ESimOne_Driver_Status_Unknown = 0u,
    ESimOne_Driver_Status_Controlling = 1u,
    ESimOne_Driver_Status_Disabled = 2u,
  };


  typedef boost::shared_ptr< ::msg_gen::SimOne_Driver_Status_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::msg_gen::SimOne_Driver_Status_<ContainerAllocator> const> ConstPtr;

}; // struct SimOne_Driver_Status_

typedef ::msg_gen::SimOne_Driver_Status_<std::allocator<void> > SimOne_Driver_Status;

typedef boost::shared_ptr< ::msg_gen::SimOne_Driver_Status > SimOne_Driver_StatusPtr;
typedef boost::shared_ptr< ::msg_gen::SimOne_Driver_Status const> SimOne_Driver_StatusConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::msg_gen::SimOne_Driver_Status_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::msg_gen::SimOne_Driver_Status_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::msg_gen::SimOne_Driver_Status_<ContainerAllocator1> & lhs, const ::msg_gen::SimOne_Driver_Status_<ContainerAllocator2> & rhs)
{
  return lhs.SimOne_Driver_Status == rhs.SimOne_Driver_Status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::msg_gen::SimOne_Driver_Status_<ContainerAllocator1> & lhs, const ::msg_gen::SimOne_Driver_Status_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace msg_gen

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::msg_gen::SimOne_Driver_Status_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msg_gen::SimOne_Driver_Status_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_gen::SimOne_Driver_Status_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_gen::SimOne_Driver_Status_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_gen::SimOne_Driver_Status_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_gen::SimOne_Driver_Status_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::msg_gen::SimOne_Driver_Status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "015bfd44c8bd98bdac9ef202c7e0f058";
  }

  static const char* value(const ::msg_gen::SimOne_Driver_Status_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x015bfd44c8bd98bdULL;
  static const uint64_t static_value2 = 0xac9ef202c7e0f058ULL;
};

template<class ContainerAllocator>
struct DataType< ::msg_gen::SimOne_Driver_Status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "msg_gen/SimOne_Driver_Status";
  }

  static const char* value(const ::msg_gen::SimOne_Driver_Status_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::msg_gen::SimOne_Driver_Status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 ESimOne_Driver_Status_Unknown = 0\n"
"uint8 ESimOne_Driver_Status_Controlling = 1\n"
"uint8 ESimOne_Driver_Status_Disabled = 2\n"
"uint32 SimOne_Driver_Status\n"
;
  }

  static const char* value(const ::msg_gen::SimOne_Driver_Status_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::msg_gen::SimOne_Driver_Status_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.SimOne_Driver_Status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SimOne_Driver_Status_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::msg_gen::SimOne_Driver_Status_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::msg_gen::SimOne_Driver_Status_<ContainerAllocator>& v)
  {
    s << indent << "SimOne_Driver_Status: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.SimOne_Driver_Status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSG_GEN_MESSAGE_SIMONE_DRIVER_STATUS_H
