// Generated by gencpp from file msg_gen/SimOne_Data_Traffic_Info.msg
// DO NOT EDIT!


#ifndef MSG_GEN_MESSAGE_SIMONE_DATA_TRAFFIC_INFO_H
#define MSG_GEN_MESSAGE_SIMONE_DATA_TRAFFIC_INFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace msg_gen
{
template <class ContainerAllocator>
struct SimOne_Data_Traffic_Info_
{
  typedef SimOne_Data_Traffic_Info_<ContainerAllocator> Type;

  SimOne_Data_Traffic_Info_()
    : id(0)
    , x(0.0)
    , y(0.0)
    , speed(0.0)
    , orientation(0.0)  {
    }
  SimOne_Data_Traffic_Info_(const ContainerAllocator& _alloc)
    : id(0)
    , x(0.0)
    , y(0.0)
    , speed(0.0)
    , orientation(0.0)  {
  (void)_alloc;
    }



   typedef int32_t _id_type;
  _id_type id;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _speed_type;
  _speed_type speed;

   typedef double _orientation_type;
  _orientation_type orientation;





  typedef boost::shared_ptr< ::msg_gen::SimOne_Data_Traffic_Info_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::msg_gen::SimOne_Data_Traffic_Info_<ContainerAllocator> const> ConstPtr;

}; // struct SimOne_Data_Traffic_Info_

typedef ::msg_gen::SimOne_Data_Traffic_Info_<std::allocator<void> > SimOne_Data_Traffic_Info;

typedef boost::shared_ptr< ::msg_gen::SimOne_Data_Traffic_Info > SimOne_Data_Traffic_InfoPtr;
typedef boost::shared_ptr< ::msg_gen::SimOne_Data_Traffic_Info const> SimOne_Data_Traffic_InfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::msg_gen::SimOne_Data_Traffic_Info_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::msg_gen::SimOne_Data_Traffic_Info_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::msg_gen::SimOne_Data_Traffic_Info_<ContainerAllocator1> & lhs, const ::msg_gen::SimOne_Data_Traffic_Info_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.speed == rhs.speed &&
    lhs.orientation == rhs.orientation;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::msg_gen::SimOne_Data_Traffic_Info_<ContainerAllocator1> & lhs, const ::msg_gen::SimOne_Data_Traffic_Info_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace msg_gen

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::msg_gen::SimOne_Data_Traffic_Info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msg_gen::SimOne_Data_Traffic_Info_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_gen::SimOne_Data_Traffic_Info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_gen::SimOne_Data_Traffic_Info_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_gen::SimOne_Data_Traffic_Info_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_gen::SimOne_Data_Traffic_Info_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::msg_gen::SimOne_Data_Traffic_Info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4c7a17b659cb37adadfae5bfebd57a6b";
  }

  static const char* value(const ::msg_gen::SimOne_Data_Traffic_Info_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4c7a17b659cb37adULL;
  static const uint64_t static_value2 = 0xadfae5bfebd57a6bULL;
};

template<class ContainerAllocator>
struct DataType< ::msg_gen::SimOne_Data_Traffic_Info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "msg_gen/SimOne_Data_Traffic_Info";
  }

  static const char* value(const ::msg_gen::SimOne_Data_Traffic_Info_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::msg_gen::SimOne_Data_Traffic_Info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 id\n"
"float64 x\n"
"float64 y\n"
"float64 speed\n"
"float64 orientation\n"
;
  }

  static const char* value(const ::msg_gen::SimOne_Data_Traffic_Info_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::msg_gen::SimOne_Data_Traffic_Info_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.speed);
      stream.next(m.orientation);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SimOne_Data_Traffic_Info_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::msg_gen::SimOne_Data_Traffic_Info_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::msg_gen::SimOne_Data_Traffic_Info_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "speed: ";
    Printer<double>::stream(s, indent + "  ", v.speed);
    s << indent << "orientation: ";
    Printer<double>::stream(s, indent + "  ", v.orientation);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSG_GEN_MESSAGE_SIMONE_DATA_TRAFFIC_INFO_H
