// Generated by gencpp from file msg_gen/vehicle_extra.msg
// DO NOT EDIT!


#ifndef MSG_GEN_MESSAGE_VEHICLE_EXTRA_H
#define MSG_GEN_MESSAGE_VEHICLE_EXTRA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace msg_gen
{
template <class ContainerAllocator>
struct vehicle_extra_
{
  typedef vehicle_extra_<ContainerAllocator> Type;

  vehicle_extra_()
    : dataSize(0)
    , extra_states()  {
    }
  vehicle_extra_(const ContainerAllocator& _alloc)
    : dataSize(0)
    , extra_states(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _dataSize_type;
  _dataSize_type dataSize;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _extra_states_type;
  _extra_states_type extra_states;





  typedef boost::shared_ptr< ::msg_gen::vehicle_extra_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::msg_gen::vehicle_extra_<ContainerAllocator> const> ConstPtr;

}; // struct vehicle_extra_

typedef ::msg_gen::vehicle_extra_<std::allocator<void> > vehicle_extra;

typedef boost::shared_ptr< ::msg_gen::vehicle_extra > vehicle_extraPtr;
typedef boost::shared_ptr< ::msg_gen::vehicle_extra const> vehicle_extraConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::msg_gen::vehicle_extra_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::msg_gen::vehicle_extra_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::msg_gen::vehicle_extra_<ContainerAllocator1> & lhs, const ::msg_gen::vehicle_extra_<ContainerAllocator2> & rhs)
{
  return lhs.dataSize == rhs.dataSize &&
    lhs.extra_states == rhs.extra_states;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::msg_gen::vehicle_extra_<ContainerAllocator1> & lhs, const ::msg_gen::vehicle_extra_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace msg_gen

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::msg_gen::vehicle_extra_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msg_gen::vehicle_extra_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_gen::vehicle_extra_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_gen::vehicle_extra_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_gen::vehicle_extra_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_gen::vehicle_extra_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::msg_gen::vehicle_extra_<ContainerAllocator> >
{
  static const char* value()
  {
    return "109ca0ebd630ab1f448483866bb7ace3";
  }

  static const char* value(const ::msg_gen::vehicle_extra_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x109ca0ebd630ab1fULL;
  static const uint64_t static_value2 = 0x448483866bb7ace3ULL;
};

template<class ContainerAllocator>
struct DataType< ::msg_gen::vehicle_extra_<ContainerAllocator> >
{
  static const char* value()
  {
    return "msg_gen/vehicle_extra";
  }

  static const char* value(const ::msg_gen::vehicle_extra_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::msg_gen::vehicle_extra_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 dataSize\n"
"float64[] extra_states\n"
;
  }

  static const char* value(const ::msg_gen::vehicle_extra_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::msg_gen::vehicle_extra_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.dataSize);
      stream.next(m.extra_states);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct vehicle_extra_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::msg_gen::vehicle_extra_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::msg_gen::vehicle_extra_<ContainerAllocator>& v)
  {
    s << indent << "dataSize: ";
    Printer<int32_t>::stream(s, indent + "  ", v.dataSize);
    s << indent << "extra_states[]" << std::endl;
    for (size_t i = 0; i < v.extra_states.size(); ++i)
    {
      s << indent << "  extra_states[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.extra_states[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSG_GEN_MESSAGE_VEHICLE_EXTRA_H
